class PaymentRepository {
  constructor(prisma){this.prisma=prisma;this.persistenceMode='POSTGRESQL';}
  transaction(callback){return this.prisma.$transaction((tx)=>callback(new PaymentRepository(tx),tx));}
  getById(organizationId,id){return this.prisma.payment.findFirst({where:{id,organizationId},include:{refunds:true,reconciliationItems:true}});}
  getByOrderId(organizationId,orderId){return this.prisma.payment.findFirst({where:{organizationId,orderId},include:{refunds:true,reconciliationItems:true}});}
  getByIdempotencyKey(organizationId,idempotencyKey){return this.prisma.payment.findUnique({where:{organizationId_idempotencyKey:{organizationId,idempotencyKey}}});}
  getByProviderReference(organizationId,provider,providerPaymentId){return this.prisma.payment.findFirst({where:{organizationId,provider,providerPaymentId}});}
  getByProviderReferenceGlobal(provider,providerPaymentId){return this.prisma.payment.findFirst({where:{provider,providerPaymentId}});}
  list(filters={},scope={}){const where=tenant(scope);for(const k of ['organizationId','status','provider'])if(filters[k])where[k]=filters[k];if(filters.dateFrom||filters.dateTo)where.createdAt={...(filters.dateFrom&&{gte:new Date(filters.dateFrom)}),...(filters.dateTo&&{lte:new Date(filters.dateTo)})};return this.prisma.payment.findMany({where,include:{reconciliationItems:{where:{status:{in:['OPEN','MANUAL_REVIEW']}}}},orderBy:{createdAt:'desc'},take:Math.min(Number(filters.limit)||100,500)});}
  create(data){return this.prisma.payment.create({data});} update(organizationId,id,data){return this.prisma.payment.updateMany({where:{organizationId,id},data});}
  createOperation(data){return this.prisma.paymentOperation.create({data});} findOperation(organizationId,operationType,idempotencyKey){return this.prisma.paymentOperation.findUnique({where:{organizationId_operationType_idempotencyKey:{organizationId,operationType,idempotencyKey}}});}
  createInbox(data){return this.prisma.paymentProviderInbox.create({data});} findInbox(provider,providerEventId){return this.prisma.paymentProviderInbox.findUnique({where:{provider_providerEventId:{provider,providerEventId}}});} getInbox(id){return this.prisma.paymentProviderInbox.findUnique({where:{id}});} updateInbox(id,data){return this.prisma.paymentProviderInbox.update({where:{id},data});}
  async claimInbox({workerId,batchSize=50,now=new Date()}){return this.transaction(async(_repo,tx)=>tx.$queryRawUnsafe(`WITH candidates AS (SELECT id FROM "PaymentProviderInbox" WHERE status IN ('RECEIVED','FAILED') AND ("nextAttemptAt" IS NULL OR "nextAttemptAt" <= $1) AND "attemptCount" < "maxAttempts" ORDER BY "receivedAt" FOR UPDATE SKIP LOCKED LIMIT $2) UPDATE "PaymentProviderInbox" i SET status='PROCESSING', "lockedAt"=$1, "lockedBy"=$3 FROM candidates WHERE i.id=candidates.id RETURNING i.*`,now,batchSize,workerId));}
  releaseExpiredInbox(before){return this.prisma.paymentProviderInbox.updateMany({where:{status:'PROCESSING',lockedAt:{lt:before}},data:{status:'FAILED',lockedAt:null,lockedBy:null,nextAttemptAt:new Date()}});}
  createRefund(data){return this.prisma.paymentRefund.create({data});} findRefundOperation(organizationId,idempotencyKey){return this.prisma.paymentRefund.findUnique({where:{organizationId_idempotencyKey:{organizationId,idempotencyKey}}});}
  createReconciliation(data){return this.prisma.paymentReconciliation.create({data});} findReconciliation(organizationId,fingerprint){return this.prisma.paymentReconciliation.findUnique({where:{organizationId_fingerprint:{organizationId,fingerprint}}});} audit(data){return this.prisma.paymentAuditEntry.create({data});} outbox(data){return this.prisma.transactionalOutboxEvent.create({data});}
}
function tenant(scope){if(scope.platform)return{};if(!scope.organizationId)throw Object.assign(new Error('Tenant scope обязателен.'),{code:'PAYMENT_TENANT_SCOPE_REQUIRED',statusCode:403});return{organizationId:scope.organizationId};}
module.exports={PaymentRepository};
