const ITEM_CATEGORY = Object.freeze({
  INGREDIENT: 'INGREDIENT',
  CONSUMABLE: 'CONSUMABLE',
  SERVICE_MATERIAL: 'SERVICE_MATERIAL',
});

const LOCATION_TYPE = Object.freeze({ WAREHOUSE: 'WAREHOUSE', MACHINE: 'MACHINE' });

const MOVEMENT_TYPE = Object.freeze({
  RECEIPT: 'RECEIPT',
  CONSUMPTION: 'CONSUMPTION',
  TEST_CONSUMPTION: 'TEST_CONSUMPTION',
  MAINTENANCE: 'MAINTENANCE',
  INVENTORY_COUNT: 'INVENTORY_COUNT',
  ADJUSTMENT: 'ADJUSTMENT',
});

const RESERVATION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  RELEASED: 'RELEASED',
  CONSUMED: 'CONSUMED',
  EXPIRED: 'EXPIRED',
});

const DIRECTION = Object.freeze({
  RECEIPT: 1,
  CONSUMPTION: -1,
  TEST_CONSUMPTION: -1,
  MAINTENANCE: -1,
});

module.exports = { ITEM_CATEGORY, LOCATION_TYPE, MOVEMENT_TYPE, RESERVATION_STATUS, DIRECTION };
