'use strict';

const TEST_MACHINE = Object.freeze({
  id: 'TEST-MACHINE-001',
  machineCode: 'TEST-MACHINE-001',
  name: 'Тестовый автомат № TEST-MACHINE-001',
});

const TEST_CATALOG = Object.freeze([
  {
    sku: 'icecream_creamy',
    category: 'ICE_CREAM',
    nameRu: 'Сливочный вкус',
    basePrice: 95,
    currency: 'RUB',
    sortOrder: 10,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: true,
  },
  {
    sku: 'topping_chocolate',
    category: 'TOPPING',
    nameRu: 'Шоколадный топпинг',
    basePrice: 25,
    currency: 'RUB',
    sortOrder: 10,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'topping_strawberry',
    category: 'TOPPING',
    nameRu: 'Клубничный топпинг',
    basePrice: 15,
    currency: 'RUB',
    sortOrder: 20,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'topping_caramel',
    category: 'TOPPING',
    nameRu: 'Карамельный топпинг',
    basePrice: 15,
    currency: 'RUB',
    sortOrder: 30,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'topping_none',
    category: 'TOPPING',
    nameRu: 'Без топпинга',
    basePrice: 0,
    currency: 'RUB',
    sortOrder: 0,
    systemItem: true,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'sprinkle_nuts',
    category: 'SPRINKLE',
    nameRu: 'Ореховый микс',
    basePrice: 25,
    currency: 'RUB',
    sortOrder: 10,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'sprinkle_confetti',
    category: 'SPRINKLE',
    nameRu: 'Конфетти',
    basePrice: 25,
    currency: 'RUB',
    sortOrder: 20,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'sprinkle_wafer',
    category: 'SPRINKLE',
    nameRu: 'Вафельная крошка',
    basePrice: 25,
    currency: 'RUB',
    sortOrder: 30,
    systemItem: false,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
  {
    sku: 'sprinkle_none',
    category: 'SPRINKLE',
    nameRu: 'Без посыпки',
    basePrice: 0,
    currency: 'RUB',
    sortOrder: 0,
    systemItem: true,
    freeItem: false,
    available: true,
    isCurrentFlavor: false,
  },
]);

module.exports = { TEST_MACHINE, TEST_CATALOG };
