import React from 'react';
import { EmptyState, StatusBadge } from './components';

export function ConnectivityCard({ connectivity }) {
  const sim = connectivity?.simCard; const plan = connectivity?.mobilePlan;
  return <section className="card"><div className="card-heading"><h2>Связь и SIM-карта</h2><TwinStatusBadge status={connectivity?.verificationStatus || 'UNKNOWN'} /></div>
    <dl className="identity-list"><dt>Оператор связи</dt><dd>{sim?.carrierName || 'Недоступно'}</dd><dt>Номер телефона</dt><dd>{sim?.phoneNumber || 'Недоступно'}</dd><dt>Тариф</dt><dd>{plan?.tariffName || 'Недоступно'}</dd><dt>Статус тарифа</dt><dd>{plan?.tariffStatus || 'UNKNOWN'}</dd><dt>Баланс</dt><dd>{plan?.currentBalance ?? 'Недоступно'} {plan?.currency || ''}</dd><dt>Следующее списание</dt><dd>{plan?.nextChargeAt ? new Date(plan.nextChargeAt).toLocaleString('ru-RU') : 'Недоступно'}</dd><dt>Остаток трафика</dt><dd>{plan?.trafficRemainingMb ?? 'Недоступно'} МБ</dd><dt>Автопополнение</dt><dd>{plan?.autoTopUpEnabled ? 'Включено' : 'Выключено'}</dd><dt>Минимальный баланс</dt><dd>{plan?.minimumBalanceThreshold ?? 'Недоступно'}</dd><dt>Последняя проверка</dt><dd>{sim?.lastCheckedAt || plan?.lastCheckedAt ? new Date(sim?.lastCheckedAt || plan?.lastCheckedAt).toLocaleString('ru-RU') : 'Недоступно'}</dd><dt>Источник данных</dt><dd>{connectivity?.sourceStatus}</dd></dl>
    {connectivity?.integrationStatus === 'BLOCKED_EXTERNAL' && <p role="alert">Интеграция с оператором недоступна</p>}
    {connectivity?.warnings?.map((warning) => <p role="alert" key={warning.code}>{warning.label}</p>)}
  </section>;
}

export const TwinStatusBadge = ({ status }) => <StatusBadge status={status || 'UNKNOWN'} />;
export function FreshnessIndicator({ freshness }) { return <div className="freshness" role="status"><TwinStatusBadge status={freshness?.status || 'UNAVAILABLE'} /><span>{freshness?.explanation || 'Сведения об актуальности недоступны.'}</span></div>; }
export function MachineTwinCard({ twin, onOpen }) { return <article className="card twin-card"><div className="card-heading"><h2>{twin.name}</h2><TwinStatusBadge status={twin.operationalStatus} /></div><p>{twin.location || 'Расположение недоступно'}</p><dl><dt>Идентификатор автомата</dt><dd>{twin.externalMachineId || twin.machineId}</dd><dt>Актуальность</dt><dd><TwinStatusBadge status={twin.freshness?.status} /></dd></dl><button className="text-button" onClick={() => onOpen?.(twin.machineId)}>Открыть цифровой двойник</button></article>; }
export function ComponentHealthCard({ component }) { return <article className="component-card"><div><strong>{component.displayName}</strong><small>{component.componentType.replaceAll('_', ' ')}</small></div><div className="health-score"><span>{component.healthScore}</span><TwinStatusBadge status={component.status} /></div></article>; }
export function ComponentList({ components = [] }) { return <section className="card"><div className="card-heading"><h2>Компоненты</h2><span>Сопоставлено: {components.length}</span></div>{components.length ? <div className="component-list">{components.map((item) => <ComponentHealthCard key={item.componentId} component={item} />)}</div> : <EmptyState title="Сопоставленных компонентов нет" />}</section>; }
export function TwinSummaryPanel({ twin }) { const metrics = [['Продажи за сутки', twin.recentSalesSummary?.count24h ?? '—'], ['Складские позиции', twin.inventorySummary?.items?.length ?? '—'], ['Открытые задачи обслуживания', twin.openServiceTasks?.length ?? 0], ['Активные неисправности', twin.activeFaults?.length ?? 0]]; return <section className="card twin-summary"><div className="card-heading"><h2>Операционная сводка</h2><TwinStatusBadge status={twin.connectivityStatus} /></div><div className="summary-grid">{metrics.map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></section>; }
export function FaultTimeline({ faults = [], events = [] }) { const rows = faults.length ? faults : events.filter((event) => event.eventType?.includes('FAULT')); return <section className="card"><div className="card-heading"><h2>Хронология неисправностей</h2><span>Событий: {rows.length}</span></div>{rows.length ? rows.map((item, index) => <div className="timeline-row" key={item.id || item.eventId || index}><TwinStatusBadge status={item.severity || 'WARNING'} /><span>{item.description || item.eventType}</span></div>) : <EmptyState title="Активных неисправностей нет" message="В этой проекции нет фактов о неисправностях." />}</section>; }
export function SnapshotHistory({ snapshots = [] }) { return <section className="card"><div className="card-heading"><h2>Снимки состояния</h2><span>Неизменяемых записей: {snapshots.length}</span></div>{snapshots.length ? snapshots.map((item) => <div className="timeline-row" key={item.snapshotId}><span>{new Date(item.generatedAt).toLocaleString('ru-RU')}</span><code>{item.snapshotId}</code></div>) : <EmptyState title="Снимки не загружены" />}</section>; }
export function SourceStatusPanel({ sources = {} }) { return <section className="card"><div className="card-heading"><h2>Доступность источников</h2><span>Проекции только для чтения</span></div><div className="source-list">{Object.entries(sources).map(([name, source]) => <div key={name}><span>{source.label || name}</span><TwinStatusBadge status={source.status} /></div>)}</div></section>; }
export function PredictionSummaryCard({ prediction }) { return <section className="card"><div className="card-heading"><h2>Прогноз состояния</h2><TwinStatusBadge status={prediction?.status || 'FOUNDATION_ONLY'} /></div><p>{prediction?.explanation || 'Прогноз недоступен.'}</p><small>Модель: {prediction?.modelVersion || 'нет'} · Только рекомендация</small></section>; }
export function MachineTwinDiagram({ components = [] }) { return <section className="card twin-diagram" aria-label="Схема автомата на основе данных"><div className="card-heading"><h2>Схема автомата</h2><span>Независимая от производителя версия 1</span></div><div className="diagram-grid">{components.map((component) => <div key={component.componentId}><TwinStatusBadge status={component.status} /><span>{component.displayName}</span></div>)}</div></section>; }
