import React, { useEffect, useState } from 'react';
import { DataTable, EmptyState, ErrorState, Skeleton, StatisticCard, StatusBadge } from './components';
import * as api from './api/organizationClient';

const roleLabels = { OWNER:'Владелец', ADMINISTRATOR:'Администратор', MANAGER:'Руководитель', OPERATOR:'Оператор', SERVICE_SPECIALIST:'Сервисный специалист', MACHINE_RESPONSIBLE:'Ответственный за аппарат', LOCATION_RESPONSIBLE:'Ответственный за точку', FINANCIALLY_RESPONSIBLE:'Финансово ответственный сотрудник' };
const date = (value) => value ? new Date(value).toLocaleDateString('ru-RU') : 'Не указана';
const money = (value) => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(value || 0);
const tabs = [['overview','Обзор'],['structure','Структура'],['members','Сотрудники'],['locations','Точки'],['machines','Аппараты'],['responsibilities','Ответственные'],['events','События'],['metrics','Показатели']];

export function OrganizationsPage({ route, clients = api }) {
  const [, organizationId, requestedTab = 'overview'] = route.split('/');
  const [state,setState]=useState({status:'loading'});
  useEffect(()=>{const controller=new AbortController(); const load=organizationId ? Promise.all([
    clients.getOrganization(organizationId,{signal:controller.signal}), clients.getOrganizationUnits(organizationId,{signal:controller.signal}), clients.getOrganizationMembers(organizationId,{signal:controller.signal}), clients.getOrganizationLocations(organizationId,{signal:controller.signal}), clients.getOrganizationMachines(organizationId,{signal:controller.signal}), clients.getOrganizationResponsibilities(organizationId,{signal:controller.signal}), clients.getOrganizationEvents(organizationId,{signal:controller.signal}), clients.getOrganizationMetrics(organizationId,{signal:controller.signal}),
  ]).then(([organization,units,members,locations,machines,responsibilities,events,metrics])=>({organization,units,members,locations,machines,responsibilities,events:events.items||events,metrics})) : clients.getOrganizations({signal:controller.signal});
  load.then(data=>setState({status:'ready',data})).catch(error=>{if(error.name!=='AbortError')setState({status:error.status===403?'denied':'error'});}); return()=>controller.abort();},[organizationId,clients]);
  if(state.status==='loading')return <Skeleton/>; if(state.status==='denied')return <ErrorState kind="denied"/>; if(state.status==='error')return <ErrorState/>;
  if(!organizationId)return <OrganizationList organizations={state.data}/>;
  return <OrganizationCard data={state.data} tab={tabs.some(([id])=>id===requestedTab)?requestedTab:'overview'}/>;
}

export function OrganizationList({organizations=[]}) { return <div className="organization-workspace"><DataTable title="Список организаций" rows={organizations} emptyTitle="Организации ещё не созданы" columns={[
  {key:'shortName',label:'Организация',render:(value,row)=><a href={`#organizations/${row.id}/overview`}>{value}</a>},{key:'organizationType',label:'Тип'},{key:'inn',label:'ИНН',render:value=>value||'Не указан'},{key:'status',label:'Статус',render:value=><StatusBadge status={value}/>} ]}/></div>; }

export function OrganizationCard({data,tab}) { const {organization,units,members,locations,machines,responsibilities,events,metrics}=data; return <div className="organization-workspace">
  <a className="back-link" href="#organizations">← Все организации</a>
  <section className="card organization-heading"><div><p>{organization.organizationType}</p><h2>{organization.fullName}</h2><span>{organization.inn?`ИНН ${organization.inn}`:'ИНН не указан'} · сотрудничество с {date(organization.cooperationStartedAt)}</span></div><StatusBadge status={organization.status}/></section>
  <nav className="detail-tabs" aria-label="Разделы организации">{tabs.map(([id,title])=><a className={tab===id?'active':''} href={`#organizations/${organization.id}/${id}`} key={id}>{title}</a>)}</nav>
  {tab==='overview'&&<Overview metrics={metrics}/>} {tab==='structure'&&<Structure units={units}/>} {tab==='members'&&<Members members={members}/>} {tab==='locations'&&<Locations locations={locations}/>} {tab==='machines'&&<Machines machines={machines}/>} {tab==='responsibilities'&&<Responsibilities items={responsibilities}/>} {tab==='events'&&<Events events={events}/>} {tab==='metrics'&&<Metrics metrics={metrics}/>} </div>; }

function Overview({metrics}) { return <section className="statistics" aria-label="Обзор организации">{[
 ['Подразделения',metrics.departments],['Сотрудники',metrics.employees],['Точки',metrics.locations],['Аппараты',metrics.machines],['Аппараты онлайн',metrics.machinesOnline,'success'],['Аппараты офлайн',metrics.machinesOffline,metrics.machinesOffline?'warning':'neutral'],['Активные инциденты',metrics.activeIncidents,metrics.activeIncidents?'critical':'neutral'],['Требуют обслуживания',metrics.machinesRequiringService,metrics.machinesRequiringService?'warning':'neutral']
 ].map(([label,value,tone])=><StatisticCard key={label} label={label} value={value ?? '—'} tone={tone}/>)}</section>; }
function Structure({units}) { const roots=units.filter(unit=>!unit.parentId); const children=(id)=>units.filter(unit=>unit.parentId===id); return <section className="card"><div className="card-heading"><h2>Структура организации</h2><span>Подразделений: {units.length}</span></div>{roots.length?<ul className="organization-tree">{roots.map(unit=><li key={unit.id}><strong>{unit.name}</strong>{children(unit.id).length>0&&<ul>{children(unit.id).map(child=><li key={child.id}>{child.name}</li>)}</ul>}</li>)}</ul>:<EmptyState title="Подразделения ещё не созданы"/>}</section>; }
function Members({members}) { return <DataTable title="Сотрудники" rows={members} columns={[{key:'fullName',label:'ФИО'},{key:'position',label:'Должность'},{key:'unit',label:'Подразделение',render:value=>value?.name||'Не назначено'},{key:'roleAssignments',label:'Роли',render:value=>value?.map(item=>roleLabels[item.role]||item.role).join(', ')||'Не назначены'},{key:'status',label:'Статус',render:value=><StatusBadge status={value}/>}]} />; }
function Locations({locations}) { return <DataTable title="Точки размещения" rows={locations} columns={[{key:'name',label:'Название'},{key:'address',label:'Адрес'},{key:'responsibleUnit',label:'Подразделение',render:value=>value?.name||'Не назначено'},{key:'responsibleMember',label:'Ответственный',render:value=>value?.fullName||'Не назначен'},{key:'machineAssignments',label:'Аппараты',render:value=>value?.length||0},{key:'status',label:'Статус',render:value=><StatusBadge status={value}/>}]} />; }
function Machines({machines}) { return <DataTable title="Аппараты организации" rows={machines} columns={[{key:'machine',label:'Аппарат',render:value=>value?.name||'Неизвестный аппарат'},{key:'location',label:'Точка',render:value=>value?.name||'Не назначена'},{key:'operatorOrganization',label:'Эксплуатирующая организация',render:value=>value?.shortName||'Не указана'},{key:'responsibleMember',label:'Ответственный',render:value=>value?.fullName||'Не назначен'},{key:'serviceSpecialist',label:'Сервисный специалист',render:value=>value?.fullName||'Не назначен'},{key:'machineStatus',label:'Статус',render:(_,row)=><StatusBadge status={row.machine?.status||'UNKNOWN'}/>}]} />; }
function Responsibilities({items}) { return <DataTable title="Назначения ответственности" rows={items} columns={[{key:'member',label:'Сотрудник',render:value=>value?.fullName},{key:'scope',label:'Область',render:value=>({ORGANIZATION:'Организация',UNIT:'Подразделение',LOCATION:'Точка',MACHINE:'Аппарат',FINANCE:'Финансы'}[value]||value)},{key:'description',label:'Зона ответственности',render:value=>value||'Не указана'},{key:'assignedAt',label:'Назначен',render:date}]} />; }
function Events({events}) { return <DataTable title="События организации" rows={events} emptyTitle="События организации пока не поступали" columns={[{key:'occurredAt',label:'Дата',render:date},{key:'title',label:'Событие',render:(value,row)=>value||row.eventType},{key:'summary',label:'Описание',render:value=>value||'Без описания'},{key:'severity',label:'Важность',render:value=><StatusBadge status={value||'INFO'}/>}]} />; }
function Metrics({metrics}) { const rows=[['Количество аппаратов',metrics.machines,'machine'],['Активные аппараты',metrics.machinesOnline,'machine'],['Аппараты офлайн',metrics.machinesOffline,'machine'],['Количество продаж',metrics.sales,'orders'],['Оборот',money(metrics.revenueRub),'orders'],['Количество клиентов',metrics.customers,'customers'],['Количество инцидентов',metrics.activeIncidents,'incidents'],['Количество сервисных работ',metrics.serviceWorks,'maintenance']].map(([name,value,source],index)=>({id:String(index),name,value:value??'—',status:metrics.sources[source]})); return <DataTable title="Показатели" rows={rows} columns={[{key:'name',label:'Показатель'},{key:'value',label:'Значение'},{key:'status',label:'Источник',render:value=><StatusBadge status={value}/>}]} />; }
