import React, { useEffect, useState } from 'react';
import { EmptyState, ErrorState, Skeleton, StatusBadge } from './components';
import { checkCamera, controlRecording, listCameras, listVideoFragments, listVideoIncidents } from './api/videoSurveillanceClient';
const dt = (v) => v ? new Date(v).toLocaleString('ru-RU') : 'Нет данных';
const mode = { CONTINUOUS: 'Непрерывная', MOTION: 'По движению', MACHINE_EVENT: 'По событию автомата', HYBRID: 'Гибридная', LIVE_ONLY: 'Только прямой эфир', DISABLED: 'Отключена' };
export function CameraSurveillancePanel({ machineId, clients = { listCameras, listVideoFragments, listVideoIncidents, checkCamera, controlRecording } }) {
  const [state, setState] = useState({ status: 'loading' }); const [notice, setNotice] = useState('');
  const load = () => Promise.all([clients.listCameras(machineId), clients.listVideoFragments(machineId), clients.listVideoIncidents(machineId)]).then(([cameras, fragments, incidents]) => setState({ status: 'ready', cameras, fragments, incidents })).catch((e) => setState({ status: [401,403].includes(e.status) ? 'denied' : 'unavailable' }));
  useEffect(() => { load(); }, [machineId]);
  if (state.status === 'loading') return <Skeleton />; if (state.status === 'denied') return <ErrorState kind="denied" />; if (state.status === 'unavailable') return <ErrorState />; if (!state.cameras.length) return <EmptyState title="Камера не установлена" message="Добавьте камеру вручную или подключите будущий edge-agent." />;
  const camera = state.cameras[0], pir = camera.sensors?.find((s) => s.sensorType === 'PIR'), health = camera.health;
  const action = async (fn, message) => { try { await fn(machineId, camera.id); setNotice(message); await load(); } catch { setNotice('Действие не выполнено. Проверьте доступ и состояние камеры.'); } };
  return <div className="video-surveillance">
    <div className="demo-marker"><StatusBadge status="FOUNDATION_ONLY" /> Метаданные и mock-адаптеры; поток RTSP в браузер не передаётся</div>
    {notice && <p role="status" className="video-notice">{notice}</p>}
    <section className="statistics" aria-label="Сводка видеонаблюдения"><article className="stat-card"><span>Камера установлена</span><strong>Да</strong></article><article className="stat-card"><span>Статус камеры</span><StatusBadge status={camera.status} /></article><article className="stat-card"><span>Активные инциденты</span><strong>{camera.activeIncidentCount}</strong></article><article className="stat-card"><span>Связанные записи</span><strong>{camera.fragmentCount}</strong></article></section>
    <section className="detail-grid"><article className="card"><div className="card-heading"><h2>{camera.name}</h2><StatusBadge status={camera.status} /></div><dl className="identity-list"><dt>Модель</dt><dd>{camera.model || 'Не указана'}</dd><dt>Расположение</dt><dd>{camera.locationDescription || 'Не указано'}</dd><dt>Режим записи</dt><dd>{mode[camera.recordingMode] || camera.recordingMode}</dd><dt>PIR-датчик</dt><dd>{pir ? `Установлен · ${pir.status}` : 'Не установлен'}</dd><dt>Последнее движение</dt><dd>{dt(pir?.lastMotionAt)}</dd><dt>Последний кадр</dt><dd>{dt(camera.lastFrameAt)}</dd><dt>Последняя проверка</dt><dd>{dt(camera.lastHealthCheckAt)}</dd><dt>Локальный архив</dt><dd>{camera.localStorageEnabled ? 'Включён' : 'Отключён'}</dd><dt>Ёмкость накопителя</dt><dd>{camera.localStorageCapacity ? `${Math.round(camera.localStorageCapacity / 1073741824)} ГБ` : 'Нет данных'}</dd><dt>Срок хранения</dt><dd>{camera.retentionHours} ч</dd></dl></article>
    <article className="card"><div className="card-heading"><h2>Проверка камеры</h2><StatusBadge status={health?.status || 'UNKNOWN'} /></div><ul className="health-check-list">{[['Сетевой узел',health?.networkReachable],['RTSP-порт',health?.rtspPortReachable],['Авторизация',health?.authorizationSuccessful],['Кадры поступают',health?.framesReceived],['Изображение не замерло',health && !health.imageFrozen],['Время синхронизировано',health?.cameraTimeSynchronized],['Накопитель доступен',health?.localStorageAvailable],['Свободного места достаточно',health?.sufficientFreeSpace]].map(([label,ok]) => <li key={label}><span>{label}</span><b>{ok == null ? 'Не проверено' : ok ? 'Да' : 'Нет'}</b></li>)}</ul></article></section>
    <div className="video-actions"><button onClick={() => action(clients.checkCamera, 'Проверка камеры завершена.')}>Проверить камеру</button><button disabled title="Доступ появится через media proxy">Открыть прямой эфир</button><button onClick={() => action(clients.controlRecording, 'Контрольная запись начата.')}>Начать контрольную запись</button><button>Создать инцидент</button><button disabled={!state.fragments.length}>Сохранить фрагмент</button><button disabled={!state.fragments.length}>Продлить хранение</button></div>
    <section className="card"><div className="card-heading"><h2>Инциденты и архив</h2><span>Хранение по умолчанию: 72 часа</span></div>{!state.incidents.length && !state.fragments.length ? <p>Инцидентов и сохранённых фрагментов нет.</p> : <ul>{state.incidents.map((i) => <li key={i.id}>{i.title} · {i.status}</li>)}{state.fragments.map((f) => <li key={f.id}>Фрагмент {f.id} · до {dt(f.retentionUntil)}</li>)}</ul>}</section>
  </div>;
}
