const GIFT_TRANSFER_STATUS = Object.freeze({
  CREATED: 'CREATED', INVITED: 'INVITED', WAITING_FOR_REGISTRATION: 'WAITING_FOR_REGISTRATION',
  AVAILABLE: 'AVAILABLE', ACCEPTED: 'ACCEPTED', REDEMPTION_READY: 'REDEMPTION_READY',
  REDEEMED: 'REDEEMED', EXPIRED: 'EXPIRED', CANCELLED: 'CANCELLED', RETURNED_TO_SENDER: 'RETURNED_TO_SENDER',
});
const INVITATION_STATUS = Object.freeze({ CREATED: 'CREATED', SENT: 'SENT', OPENED: 'OPENED', REGISTERED: 'REGISTERED', CLAIMED: 'CLAIMED', EXPIRED: 'EXPIRED', CANCELLED: 'CANCELLED' });
const REFERRAL_STAGE = Object.freeze({ INVITED: 'INVITED', REGISTERED: 'REGISTERED', GIFT_ACCEPTED: 'GIFT_ACCEPTED', GIFT_REDEEMED: 'GIFT_REDEEMED', FIRST_OWN_PURCHASE: 'FIRST_OWN_PURCHASE' });
const DELIVERY_STATUS = Object.freeze({ QUEUED: 'QUEUED', SENT: 'SENT', DELIVERED: 'DELIVERED', OPENED: 'OPENED', FAILED: 'FAILED', UNAVAILABLE: 'UNAVAILABLE', UNKNOWN: 'UNKNOWN' });
module.exports = { GIFT_TRANSFER_STATUS, INVITATION_STATUS, REFERRAL_STAGE, DELIVERY_STATUS };
