const crypto = require('crypto');
const { ApiError } = require('../../platform/errors/ApiError');
const { normalizePhone } = require('../customer/CustomerEntity');
const { GIFT_TRANSFER_STATUS, INVITATION_STATUS, REFERRAL_STAGE } = require('./GiftTransferModels');
const ACTIVE_ORDER_STATUSES = ['PAID'];
const EVENT_CODES = ['PREPAID_ORDER_CANCEL_REQUESTED','PREPAID_ORDER_CANCELLED_TO_BALANCE','GIFT_TRANSFER_CREATED','GIFT_INVITATION_CREATED','GIFT_INVITATION_SENT','GIFT_INVITATION_OPENED','GIFT_RECIPIENT_REGISTERED','GIFT_TRANSFER_AVAILABLE','GIFT_ACCEPTED','GIFT_REDEMPTION_REQUESTED','GIFT_REDEMPTION_CODE_ISSUED','GIFT_REDEEMED','GIFT_TRANSFER_CANCELLED','GIFT_EXPIRED','GIFT_RETURNED_TO_SENDER','REFERRAL_CREATED_FROM_GIFT','REFERRAL_FIRST_OWN_PURCHASE_COMPLETED'];
class GiftTransferService {
  constructor({ repository, orderRepository, customerRepository, clubAccountRuntime, notificationOrchestrator, eventPublisher, auditRepository = null, clock = () => new Date(), tokenFactory = () => crypto.randomBytes(32).toString('base64url') }) {
    Object.assign(this, { repository, orderRepository, customerRepository, clubAccountRuntime, notificationOrchestrator, eventPublisher, auditRepository, clock, tokenFactory }); this.invitationAttempts = new Map(); this.pendingOrders = new Set();
  }
  async giftOptions(customerId, orderId) { const order = await this.ownOrder(customerId, orderId); return { orderId, canCancelToBalance: order.status === 'PAID', canGift: order.status === 'PAID' && !this.repository.findActiveByOrderId(orderId), expiresAt: order.expiresAt || null }; }
  async cancelPrepaidOrderToBalance(customerId, orderId, context = {}) {
    const correlationId = context.correlationId || crypto.randomUUID(); const order = await this.ownOrder(customerId, orderId);
    if (order.status === 'CANCELLED_BY_CUSTOMER' && order.cancelledToBalanceAt) return { order, changed: false };
    this.assertPaidAndUnfulfilled(order); if (this.repository.findActiveByOrderId(orderId)) throw conflict('GIFT_TRANSFER_ACTIVE', 'Сначала отмените передачу подарка.');
    await this.emit('PREPAID_ORDER_CANCEL_REQUESTED', orderId, correlationId, { customerId, orderId });
    const balance = await this.clubAccountRuntime.creditOrderReturn(customerId, order, { ...context, correlationId, idempotencyKey: `prepaid-order-return:${orderId}` });
    const cancelled = await this.orderRepository.cancelPrepaidToBalance(orderId, this.clock());
    await this.emit('PREPAID_ORDER_CANCELLED_TO_BALANCE', orderId, correlationId, { customerId, orderId, balanceTransactionId: balance.transaction.id });
    return { order: cancelled, balanceTransaction: balance.transaction, changed: true };
  }
  async createGift(customerId, orderId, request, context = {}) {
    const order = await this.ownOrder(customerId, orderId);
    if (this.repository.findByOrderId(orderId) || this.pendingOrders.has(orderId)) throw conflict('GIFT_TRANSFER_ALREADY_EXISTS', 'Для этого заказа передача уже создавалась.');
    this.assertPaidAndUnfulfilled(order);
    const phone = normalizePhone(request.recipientPhone); if (!phone) throw validation('recipientPhone', 'Введите телефон в формате +7 (XXX) XXX-XX-XX');
    const sender = await this.customerRepository.findById(customerId); if (sender?.phone === phone) throw conflict('GIFT_TO_SELF_NOT_ALLOWED', 'Нельзя подарить заказ самому себе');
    this.pendingOrders.add(orderId);
    try {
    this.checkRateLimit(customerId); const now = this.clock(); const correlationId = context.correlationId || crypto.randomUUID(); const recipient = await this.customerRepository.findByVerifiedPhone(phone);
    const token = this.tokenFactory(); const tokenHash = sha256(token); const id = `gift_${crypto.randomUUID()}`;
    const reservedOrder = this.orderRepository.reserveForGift ? await this.orderRepository.reserveForGift(orderId) : order;
    if (!reservedOrder) throw conflict('ORDER_NOT_PREPAID', 'Заказ уже недоступен для передачи.');
    const transfer = this.repository.saveTransfer({ id, originalOrderId: orderId, senderCustomerId: customerId, recipientCustomerId: recipient?.id || null,
      recipientPhoneNormalized: phone, status: recipient ? GIFT_TRANSFER_STATUS.AVAILABLE : GIFT_TRANSFER_STATUS.WAITING_FOR_REGISTRATION,
      referralId: null, invitationTokenHash: tokenHash, createdAt: now, acceptedAt: null, redeemedAt: null,
      expiredAt: null, cancelledAt: null, transferredBy: customerId, correlationId, expiresAt: order.expiresAt || request.expiresAt || new Date(now.getTime() + 86400000), metadata: { senderName: sender?.name || null } });
    const invitation = this.repository.saveInvitation({ id: `invitation_${crypto.randomUUID()}`, giftTransferId: id, recipientPhoneNormalized: phone, tokenHash,
      expiresAt: transfer.expiresAt, status: INVITATION_STATUS.CREATED, createdAt: now, acceptedAt: null, metadata: {} });
    transfer.referralId = `gift_referral_${crypto.randomUUID()}`; this.repository.saveReferral({ id: transfer.referralId, giftTransferId: id, referralSource: 'GIFT_TRANSFER', stage: REFERRAL_STAGE.INVITED, referrerCustomerId: customerId, referredCustomerId: recipient?.id || null, createdAt: now, firstOwnPurchaseAt: null, metadata: {} });
    await this.emit('GIFT_TRANSFER_CREATED', id, correlationId, { orderId, senderCustomerId: customerId }); await this.emit('GIFT_INVITATION_CREATED', id, correlationId, { invitationId: invitation.id });
    if (recipient) await this.emit('GIFT_TRANSFER_AVAILABLE', id, correlationId, { recipientCustomerId: recipient.id });
    const notification = { id: `notification_${crypto.randomUUID()}`, giftTransferId: id, recipientCustomerId: recipient?.id || null, recipientPhoneNormalized: phone,
      channels: ['TELEGRAM','MAX'], template: 'GIFT_INVITATION', title: 'Вам подарили мороженое 🎁', actionToken: token, correlationId };
    const deliveries = await this.notificationOrchestrator.send(notification); invitation.status = INVITATION_STATUS.SENT;
    await this.emit('GIFT_INVITATION_SENT', id, correlationId, { invitationId: invitation.id, notificationId: notification.id });
    await this.audit('GiftTransfer.Created', customerId, transfer.id, 'create', 'success', context);
    return { giftTransfer: publicGift(transfer), invitation: { id: invitation.id, giftTransferId: id, status: invitation.status, expiresAt: invitation.expiresAt }, deliveries };
    } finally { this.pendingOrders.delete(orderId); }
  }
  async claimInvitation(customerId, token, context = {}) {
    const hash = sha256(token); const invitation = this.repository.findInvitationByTokenHash(hash); if (!invitation || ['CLAIMED','EXPIRED','CANCELLED'].includes(invitation.status)) throw conflict('INVITATION_TOKEN_INVALID', 'Приглашение недействительно или уже использовано.');
    const customer = await this.customerRepository.findById(customerId); if (!customer?.phoneVerified || customer.phone !== invitation.recipientPhoneNormalized) throw conflict('RECIPIENT_PHONE_MISMATCH', 'Подарок доступен только владельцу указанного подтверждённого номера.');
    if (new Date(invitation.expiresAt) <= this.clock()) throw conflict('GIFT_EXPIRED', 'Срок действия подарка истёк.');
    const transfer = this.repository.findById(invitation.giftTransferId); transfer.recipientCustomerId = customerId; transfer.status = GIFT_TRANSFER_STATUS.AVAILABLE; invitation.status = INVITATION_STATUS.CLAIMED; invitation.acceptedAt = this.clock();
    const referral = this.repository.referrals.get(transfer.referralId); referral.referredCustomerId = customerId; referral.stage = REFERRAL_STAGE.REGISTERED;
    await this.emit('GIFT_RECIPIENT_REGISTERED', transfer.id, transfer.correlationId, { recipientCustomerId: customerId }); await this.emit('REFERRAL_CREATED_FROM_GIFT', transfer.id, transfer.correlationId, { referralId: referral.id });
    return transfer;
  }
  async accept(customerId, giftId) { const gift = this.ownGift(customerId, giftId); if (gift.status === 'ACCEPTED' || gift.status === 'REDEMPTION_READY') return gift; if (gift.status !== 'AVAILABLE') throw conflict('GIFT_ACCEPT_NOT_ALLOWED', 'Подарок сейчас нельзя принять.'); gift.status = 'ACCEPTED'; gift.acceptedAt = this.clock(); this.repository.referrals.get(gift.referralId).stage = REFERRAL_STAGE.GIFT_ACCEPTED; await this.emit('GIFT_ACCEPTED', gift.id, gift.correlationId, { recipientCustomerId: customerId }); return gift; }
  async requestRedemption(customerId, giftId) { const gift = this.ownGift(customerId, giftId); if (!['ACCEPTED','REDEMPTION_READY'].includes(gift.status)) throw conflict('GIFT_REDEMPTION_NOT_ALLOWED', 'Сначала примите подарок.'); if (new Date(gift.expiresAt) <= this.clock()) return this.expire(gift.id); const order = await this.orderRepository.findById(gift.originalOrderId); if (order.status !== 'GIFT_TRANSFERRED') throw conflict('GIFT_ORDER_STATE_INVALID', 'Заказ недоступен для получения подарка.'); const existing = [...this.repository.redemptions.values()].find((x) => x.giftTransferId === gift.id && !x.usedAt && new Date(x.expiresAt) > this.clock()); if (existing) return { ...existing, machineContract: existing.metadata.machineContract }; await this.emit('GIFT_REDEMPTION_REQUESTED', gift.id, gift.correlationId, {}); const code = String(crypto.randomInt(100000, 1000000)); const expiresAt = new Date(this.clock().getTime() + 300000); const machineContract = { status: 'FOUNDATION_ONLY', giftId: gift.id, orderId: gift.originalOrderId, recipientCustomerId: customerId, machineId: order.machineId || null, eligible: true, giftExpiresAt: gift.expiresAt, authorizationExpiresAt: expiresAt, singleUse: true, dispenseResult: 'PENDING_EXTERNAL_RUNTIME' }; const redemption = this.repository.saveRedemption({ id: `redemption_${crypto.randomUUID()}`, giftTransferId: gift.id, recipientCustomerId: customerId, authorizationHash: sha256(code), status: 'ISSUED', issuedAt: this.clock(), expiresAt, usedAt: null, correlationId: gift.correlationId, metadata: { machineContract } }); gift.status = 'REDEMPTION_READY'; await this.emit('GIFT_REDEMPTION_CODE_ISSUED', gift.id, gift.correlationId, { redemptionId: redemption.id, machineId: machineContract.machineId }); return { ...redemption, code, machineContract }; }
  async redeem(giftId, code, result = {}) { const gift = this.repository.findById(giftId); const redemption = [...this.repository.redemptions.values()].find((x) => x.giftTransferId === giftId && x.authorizationHash === sha256(code)); if (!gift || gift.status !== 'REDEMPTION_READY' || !redemption || redemption.usedAt || new Date(redemption.expiresAt) <= this.clock() || new Date(gift.expiresAt) <= this.clock()) throw conflict('REDEMPTION_CODE_INVALID', 'Код недействителен или уже использован.'); if (result.dispenseResult !== 'SUCCESS') throw conflict('MACHINE_DISPENSE_NOT_CONFIRMED', 'Выдача автоматом не подтверждена.'); const completed = this.orderRepository.completeGift ? await this.orderRepository.completeGift(gift.originalOrderId) : true; if (!completed) throw conflict('GIFT_ORDER_STATE_INVALID', 'Заказ недоступен для завершения выдачи.'); redemption.usedAt = this.clock(); redemption.status = 'REDEEMED'; redemption.metadata.machineContract.dispenseResult = 'SUCCESS'; gift.status = 'REDEEMED'; gift.redeemedAt = this.clock(); this.repository.referrals.get(gift.referralId).stage = REFERRAL_STAGE.GIFT_REDEEMED; await this.emit('GIFT_REDEEMED', gift.id, gift.correlationId, { redemptionId: redemption.id, machineId: result.machineId || null, dispenseResult: 'SUCCESS' }); return gift; }
  async cancel(customerId, giftId) { const gift = this.repository.findById(giftId); if (!gift || gift.senderCustomerId !== customerId) throw notFound(); if (gift.acceptedAt) throw conflict('GIFT_ALREADY_ACCEPTED', 'После принятия подарка отменить передачу нельзя.'); if (gift.status === 'CANCELLED') return gift; if (this.orderRepository.releaseGift) await this.orderRepository.releaseGift(gift.originalOrderId); gift.status = 'CANCELLED'; gift.cancelledAt = this.clock(); const invitation = [...this.repository.invitations.values()].find((x) => x.giftTransferId === gift.id); if (invitation) invitation.status = 'CANCELLED'; await this.emit('GIFT_TRANSFER_CANCELLED', gift.id, gift.correlationId, {}); return gift; }
  async expire(giftId) { const gift = this.repository.findById(giftId); if (!gift) throw notFound(); if (gift.status === 'RETURNED_TO_SENDER') return gift; gift.status = 'EXPIRED'; gift.expiredAt = this.clock(); await this.emit('GIFT_EXPIRED', gift.id, gift.correlationId, {}); const order = await this.orderRepository.findById(gift.originalOrderId); await this.clubAccountRuntime.creditOrderReturn(gift.senderCustomerId, order, { correlationId: gift.correlationId, idempotencyKey: `gift-expiry-return:${gift.id}`, actorType: 'system', actorId: 'gift_transfer_runtime', reason: 'gift_expired' }); await this.orderRepository.cancelPrepaidToBalance(order.id, this.clock()); gift.status = 'RETURNED_TO_SENDER'; await this.emit('GIFT_RETURNED_TO_SENDER', gift.id, gift.correlationId, {}); return gift; }
  listOwn(customerId) { return this.repository.listForCustomer(customerId).map(publicGift); } getOwn(customerId, id) { const gift = this.repository.findById(id); if (!gift || ![gift.senderCustomerId,gift.recipientCustomerId].includes(customerId)) throw notFound(); return publicGift(gift); }
  statistics() { const list = this.repository.list(); const invited = list.length; const registered = list.filter((x) => x.recipientCustomerId).length; const first = [...this.repository.referrals.values()].filter((x) => x.stage === REFERRAL_STAGE.FIRST_OWN_PURCHASE).length; return { sentGifts: invited, acceptedGifts: list.filter((x) => x.acceptedAt).length, activatedGiftReferrals: registered, firstOwnPurchases: first, giftToRegistrationConversion: invited ? registered / invited : 0, giftToFirstPurchaseConversion: invited ? first / invited : 0 }; }
  async ownOrder(customerId, orderId) { const order = await this.orderRepository.findByIdForCustomer(orderId, customerId); if (!order) throw notFound(); return order; }
  ownGift(customerId, id) { const gift = this.repository.findById(id); if (!gift || gift.recipientCustomerId !== customerId) throw notFound(); return gift; }
  assertPaidAndUnfulfilled(order) { if (!ACTIVE_ORDER_STATUSES.includes(order.status) || order.paymentStatus !== 'paid') throw conflict('ORDER_NOT_PREPAID', 'Заказ должен быть оплачен и доступен для получения.'); if (order.dispenseRequest && ['REQUESTED','IN_PROGRESS','COMPLETED'].includes(order.dispenseRequest.state)) throw conflict('ORDER_FULFILLMENT_ACTIVE', 'Выдача уже начата или завершена.'); }
  checkRateLimit(customerId) { const now = this.clock().getTime(); const recent = (this.invitationAttempts.get(customerId) || []).filter((x) => now - x < 3600000); if (recent.length >= 5) throw conflict('GIFT_INVITATION_RATE_LIMIT', 'Слишком много приглашений. Повторите позже.'); recent.push(now); this.invitationAttempts.set(customerId, recent); }
  emit(code, id, correlationId, payload) { return this.eventPublisher?.publish({ type: code, name: code, eventType: code, eventVersion: 1,
    aggregateType: 'GIFT_TRANSFER', aggregateId: id, actorType: payload.customerId || payload.senderCustomerId || payload.recipientCustomerId ? 'CUSTOMER' : 'SYSTEM',
    actorId: payload.customerId || payload.senderCustomerId || payload.recipientCustomerId || 'gift_transfer_runtime', sourceChannel: 'GIFT_TRANSFER_RUNTIME',
    correlationId, idempotencyKey: `${code}:${id}`, payload, metadata: { eventCenter: true, sourceDomain: 'gift_transfer' } }); }
  audit(eventType, customerId, targetId, action, decision, context) { return this.auditRepository?.record({ eventType, subjectType: 'user', subjectId: customerId, targetType: 'GiftTransfer', targetId, action, decision, reasonCode: 'gift_transfer', authMethod: context.authMethod, sourceChannel: context.sourceChannel, correlationId: context.correlationId, metadata: {} }); }
}
function sha256(value) { return crypto.createHash('sha256').update(String(value)).digest('hex'); }
function maskPhone(value) { return value ? `${value.slice(0, 2)} *** ***-${value.slice(-4, -2)}-${value.slice(-2)}` : null; }
function publicGift(value) { const { invitationTokenHash, recipientPhoneNormalized, ...safe } = value; return { ...safe, recipientPhoneMasked: maskPhone(recipientPhoneNormalized) }; }
function conflict(code, message) { return new ApiError({ statusCode: 409, code, message, source: 'runtime' }); } function notFound() { return new ApiError({ statusCode: 404, code: 'RESOURCE_NOT_FOUND', message: 'Подарок или заказ не найден.', source: 'runtime' }); } function validation(field, issue) { return new ApiError({ statusCode: 400, code: 'VALIDATION_FAILED', message: 'Проверьте введённые данные.', details: [{ field, issue }], source: 'api' }); }
module.exports = { GiftTransferService, EVENT_CODES, sha256 };
