import React, { useEffect, useMemo, useState } from 'react';
import { operatorWorkspaceApi as api } from './OperatorWorkspaceApi.js';

const TESTS = { CUP: 'Выдать тестовый стаканчик', ICE_CREAM: 'Проверить выдачу мороженого', SYRUP: 'Проверить выдачу сиропов' };
const ACTIONS = { SessionOpened: 'Начато обслуживание', ChecklistUpdated: 'Обновлён чек-лист', PhotoAttached: 'Добавлена фотография', TestPerformed: 'Выполнена тестовая операция', ConsumableWrittenOff: 'Списаны материалы', SessionCompleted: 'Завершено обслуживание' };

export function OperatorWorkspacePage() {
  const [view, setView] = useState('list'), [machines, setMachines] = useState([]), [machine, setMachine] = useState(), [session, setSession] = useState(), [actions, setActions] = useState([]), [message, setMessage] = useState('');
  useEffect(() => { api.listMachines().then(setMachines).catch((error) => setMessage(error.message)); }, []);
  async function act(operation, success) { try { setMessage(''); const result = await operation(); if (success) setMessage(success); return result; } catch (error) { setMessage(error.message); } }
  async function select(id) { const result = await act(() => api.getMachine(id)); if (result) { setMachine(result); setView('machine'); } }
  async function start() { const result = await act(() => api.openSession(machine.id), 'Обслуживание начато'); if (result) { setSession(result); setView('service'); } }
  async function update(item, status) { const result = await act(() => api.checklist(session.id, item.id, status)); if (result) setSession(result); }
  async function photo(stage, file) { if (!file) return; const result = await act(() => api.photo(session.id, stage, file), 'Фотография сохранена'); if (result) setSession(result); }
  async function test(type) { const result = await act(() => api.test(session.id, type), 'Тестовый расход записан отдельно от продаж'); if (result) setSession(result); }
  async function consume(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await act(() => api.consume(session.id, Object.fromEntries(form)), 'Списание зафиксировано'); if (result) { setSession(result); event.currentTarget.reset(); } }
  async function complete() { const result = await act(() => api.complete(session.id), 'Обслуживание завершено'); if (result) setSession(result); }
  async function journal() { const result = await act(() => api.actions(machine?.id)); if (result) { setActions(result); setView('journal'); } }
  const progress = useMemo(() => !session ? 0 : Math.round((session.checklist.filter((x) => x.status !== 'PENDING').length + Math.min(1, session.photos.before.length) + Math.min(1, session.photos.after.length) + new Set(session.tests.map((x) => x.type)).size) / (session.checklist.length + 2 + session.availableTests.length) * 100), [session]);
  return <main className="operator-shell">
    <header className="operator-header"><div><p>Рабочее место оператора</p><h1>{view === 'list' ? 'Мой маршрут' : machine?.name || 'Журнал действий'}</h1></div><button onClick={() => { setView('list'); setMachine(); setSession(); }}>ОИ</button></header>
    {message && <div className="operator-notice">{message}</div>}
    {view === 'list' && <section><div className="operator-count"><b>{machines.length}</b> автомата назначено сегодня</div><div className="operator-grid">{machines.map((item) => <button className="machine-card" key={item.id} onClick={() => select(item.id)}><i className={item.status === 'Готов к работе' ? 'ok' : ''}/><span><strong>{item.name}</strong><small>{item.address}</small><em>{item.status}</em></span><b>›</b></button>)}</div><button className="operator-link" onClick={journal}>Открыть журнал действий</button></section>}
    {view === 'machine' && machine && <section className="operator-stack"><button className="operator-link" onClick={() => setView('list')}>← Назад к маршруту</button><article><code>{machine.code}</code><h2>{machine.status}</h2><p>{machine.address}</p><dl><dt>Последнее обслуживание</dt><dd>{new Date(machine.lastServiceAt).toLocaleString('ru-RU')}</dd><dt>Сиропные линии</dt><dd>{machine.syrupLines.join(', ') || 'Не установлены'}</dd></dl></article><article><h2>Остатки</h2>{machine.consumables.map((x) => <div className="stock" key={x.itemId}><span>{x.name}</span><b>{x.level} {x.unit}</b></div>)}</article><button className="operator-primary" onClick={start}>Начать обслуживание</button><button className="operator-secondary" onClick={journal}>Журнал автомата</button></section>}
    {view === 'service' && session && <section className="operator-stack"><div className="operator-progress"><span style={{width:`${progress}%`}}/><b>{progress}%</b></div><Panel title="Фото до обслуживания"><Photo stage="BEFORE" done={session.photos.before.length} onChange={photo}/></Panel><Panel title="Чек-лист">{session.checklist.map((item) => <label className="operator-check" key={item.id}><input type="checkbox" checked={item.status !== 'PENDING'} onChange={(e) => update(item, e.target.checked ? 'PASSED' : 'NOT_APPLICABLE')}/>{item.label}</label>)}</Panel><Panel title="Тестовые операции"><p>Расход учитывается отдельно от коммерческих продаж.</p>{session.availableTests.map((type) => <button className="operator-test" disabled={session.tests.some((x) => x.type === type)} onClick={() => test(type)} key={type}>{session.tests.some((x) => x.type === type) ? '✓ ' : ''}{TESTS[type]}</button>)}</Panel><Panel title="Списание материалов"><form className="operator-form" onSubmit={consume}><input required name="item_id" pattern="[a-z][a-z0-9_-]*" placeholder="Технический код"/><input required name="name" placeholder="Материал"/><input required name="quantity" type="number" min=".01" step=".01" placeholder="Количество"/><input required name="unit" placeholder="Ед. изм."/><input type="hidden" name="reason" value="Расход при обслуживании"/><button className="operator-secondary">Зафиксировать списание</button></form></Panel><Panel title="Фото после обслуживания"><Photo stage="AFTER" done={session.photos.after.length} onChange={photo}/></Panel><button className="operator-primary" disabled={session.status === 'COMPLETED'} onClick={complete}>{session.status === 'COMPLETED' ? 'Обслуживание завершено' : 'Завершить обслуживание'}</button></section>}
    {view === 'journal' && <section className="operator-stack"><button className="operator-link" onClick={() => setView(machine ? 'machine' : 'list')}>← Назад</button><article><h2>Журнал действий</h2>{actions.map((x) => <div className="journal" key={x.id}><b>{ACTIONS[x.eventType.split('.').at(-1)] || x.eventType}</b><span>{new Date(x.occurredAt).toLocaleString('ru-RU')}</span></div>)}</article></section>}
  </main>;
}
function Panel({title, children}) { return <article><h2>{title}</h2>{children}</article>; }
function Photo({stage, done, onChange}) { return <label className={`operator-photo ${done ? 'done' : ''}`}><input type="file" accept="image/*" capture="environment" onChange={(e) => onChange(stage, e.target.files[0])}/>{done ? '✓ Фото добавлено' : '📷 Добавить фотографию'}</label>; }
