import React, { useEffect, useMemo, useRef, useState } from 'react';
import { trackEvent } from '../analytics/trackEvent.js';
import { PromotionPricePanel } from '../promotion/PromotionPricePanel.jsx';
import { PromotionPreStartBanner } from '../promotion/PromotionPreStartBanner.jsx';
import { TerminalPromotionHero } from '../promotion/PromotionAwareness.jsx';
import { resolveMachineId } from '../promotion/PricingQuoteApi.js';
import { usePricingQuote } from '../promotion/usePricingQuote.js';
import { usePromotionAwareness } from '../promotion/usePromotionAwareness.js';
import { salesTerminalService } from './SalesTerminalService.js';

const STEP_LABELS = ['Выбор', 'Оплата', 'Выдача'];
const BASE_PRODUCT_IMAGE_URL = '/product-base.png';
const IDLE_TIMEOUT_MS = 3 * 60 * 1000;
const QR_TTL_SECONDS = 300;

function BrandMark() { return <div className="terminal-brand"><span className="terminal-logo" aria-hidden="true">🍦</span><span><strong>У Тимоши</strong><small>панель продаж</small></span></div>; }
function Stepper({ step }) { return <ol className="terminal-stepper" aria-label="Этапы покупки">{STEP_LABELS.map((label, index) => <li className={index <= step ? 'is-active' : ''} key={label}><span>{index + 1}</span>{label}</li>)}</ol>; }
function ChoiceCard({ active, children, onClick }) { return <button className={active ? 'terminal-choice is-selected' : 'terminal-choice'} type="button" onClick={onClick}>{children}<span className="choice-check" aria-hidden="true">{active ? '✓' : ''}</span></button>; }
function ProductArtwork({ compact = false }) { return <div className={compact ? 'terminal-product-image compact' : 'terminal-product-image'}><img src={BASE_PRODUCT_IMAGE_URL} alt="Мягкое мороженое У Тимоши в фирменном стаканчике" /></div>; }
function QrPattern() { return <svg className="payment-qr" viewBox="0 0 120 120" role="img" aria-label="Демонстрационный QR-код оплаты"><rect width="120" height="120" rx="12" fill="#fff" /><path fill="#241b16" d="M10 10h34v34H10zm8 8v18h18V18zM76 10h34v34H76zm8 8v18h18V18zM10 76h34v34H10zm8 8v18h18V84zM54 12h10v10H54zm0 20h10v20H44V42h10zm18 22h12v10H72zm20 0h18v10H92zM48 68h12v12H48zm20 0h10v20H68zm20 0h22v10H98v12H86V78h2zM48 90h12v20H48zm20 8h12v12H68zm20 0h22v12H88z" /></svg>; }
function formatTimer(seconds) { const min = Math.floor(seconds / 60); const sec = String(seconds % 60).padStart(2, '0'); return `${min}:${sec}`; }
function formatPhone(digits) { const d = digits.slice(0, 10); let out = '+7'; if (d.length) out += ` (${d.slice(0, 3)}`; if (d.length >= 3) out += ')'; if (d.length > 3) out += ` ${d.slice(3, 6)}`; if (d.length > 6) out += `-${d.slice(6, 8)}`; if (d.length > 8) out += `-${d.slice(8, 10)}`; return out; }
function IdleScreen({ onExit }) { return <div className="terminal-idle" role="button" tabIndex={0} onClick={onExit} onKeyDown={onExit}><div className="terminal-idle-card"><img src={BASE_PRODUCT_IMAGE_URL} alt="Мороженое У Тимоши" /><div className="terminal-idle-copy"><p className="terminal-kicker">У Тимоши</p><h1>Счастье в одном стаканчике</h1><p>Мягкое мороженое — приготовим прямо сейчас.</p><span className="terminal-idle-touch">Коснитесь экрана, чтобы начать</span></div></div></div>; }
function LoyaltyModal({ phoneDigits, setPhoneDigits, onContinue, onSkip }) {
  const addDigit = (digit) => setPhoneDigits((value) => value.length < 10 ? value + digit : value);
  const erase = () => setPhoneDigits((value) => value.slice(0, -1));
  useEffect(() => { const onKey = (event) => { if (/^[0-9]$/.test(event.key)) addDigit(event.key); if (event.key === 'Backspace') erase(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  return <div className="terminal-modal-backdrop"><section className="terminal-modal terminal-phone-modal" role="dialog" aria-modal="true" aria-labelledby="loyalty-title"><p className="terminal-kicker">Клуб Тимоши</p><h2 id="loyalty-title">Хотите получать бонусы?</h2><p>Введите номер телефона. Это необязательно — покупку можно продолжить без регистрации.</p><div className="terminal-phone-display" aria-label="Номер телефона">{formatPhone(phoneDigits)}<span className="terminal-phone-placeholder">{phoneDigits.length < 10 ? ' ' + '_'.repeat(10 - phoneDigits.length) : ''}</span></div><div className="terminal-keypad">{['1','2','3','4','5','6','7','8','9'].map((digit) => <button type="button" key={digit} onClick={() => addDigit(digit)}>{digit}</button>)}<button type="button" className="keypad-clear" onClick={() => setPhoneDigits('')}>C</button><button type="button" onClick={() => addDigit('0')}>0</button><button type="button" className="keypad-back" onClick={erase}>⌫</button></div><div className="terminal-modal-actions"><button className="terminal-ok" type="button" disabled={phoneDigits.length !== 10} onClick={onContinue}>ОК</button><button className="terminal-secondary" type="button" onClick={onSkip}>Оплатить без бонусов</button></div></section></div>;
}

export function SalesTerminalPage() {
  const catalog = useMemo(() => salesTerminalService.getCatalogView(), []);
  const machineId = useMemo(() => resolveMachineId(), []);
  const [syrupId, setSyrupId] = useState('syrup_none');
  const [toppingId, setToppingId] = useState('topping_none');
  const [methodId, setMethodId] = useState('sbp');
  const [step, setStep] = useState(0);
  const [selectionStage, setSelectionStage] = useState('base');
  const [payment, setPayment] = useState(null);
  const [quoteRefreshKey, setQuoteRefreshKey] = useState(0);
  const [loyaltyOpen, setLoyaltyOpen] = useState(false);
  const [phoneDigits, setPhoneDigits] = useState('');
  const [idle, setIdle] = useState(false);
  const [serviceOpen, setServiceOpen] = useState(false);
  const [cancelOpen, setCancelOpen] = useState(false);
  const [qrSeconds, setQrSeconds] = useState(QR_TTL_SECONDS);
  const idleTimer = useRef(null);
  const serviceClicks = useRef([]);
  const preview = useMemo(() => salesTerminalService.createOrderPreview({ syrupId, toppingId }), [syrupId, toppingId]);
  const awareness = usePromotionAwareness({ machineId, channel: 'TERMINAL' });
  const pricing = usePricingQuote({ machineId, channel: 'TERMINAL', productId: catalog.product.id, productName: catalog.product.name.ru, refreshKey: quoteRefreshKey });
  const syrup = catalog.syrups.find(({ id }) => id === syrupId);
  const topping = catalog.toppings.find(({ id }) => id === toppingId);
  const serverPrice = pricing.status === 'ready' && pricing.quote && !pricing.lockExpired ? Number(pricing.quote.finalAmount) : preview.pricing.finalPrice;
  const canPay = pricing.status === 'ready' && !pricing.lockExpired;

  function armIdle() { clearTimeout(idleTimer.current); if (step === 0 && !loyaltyOpen && !serviceOpen) idleTimer.current = setTimeout(() => { setIdle(true); setSelectionStage('base'); trackEvent('TerminalIdleStarted', { machine_id: machineId }); }, IDLE_TIMEOUT_MS); }
  useEffect(() => { const events = ['pointerdown', 'keydown', 'touchstart']; const reset = () => { if (!idle) armIdle(); }; events.forEach((name) => window.addEventListener(name, reset, { passive: true })); armIdle(); return () => { clearTimeout(idleTimer.current); events.forEach((name) => window.removeEventListener(name, reset)); }; }, [step, loyaltyOpen, serviceOpen, idle]);
  useEffect(() => { if (step !== 1 || methodId !== 'sbp' || !payment?.paymentRequired) return undefined; setQrSeconds(QR_TTL_SECONDS); const timer = window.setInterval(() => setQrSeconds((value) => value > 0 ? value - 1 : 0), 1000); return () => window.clearInterval(timer); }, [step, methodId, payment?.orderId, payment?.paymentRequired]);

  function exitIdle() { setIdle(false); setSelectionStage('base'); armIdle(); trackEvent('TerminalIdleExitTouch', { machine_id: machineId }); }
  function refreshQuote() { setQuoteRefreshKey((value) => value + 1); trackEvent('PricingQuoteRefreshRequested', { machine_id: machineId, channel: 'TERMINAL' }); }
  function requestPayment() { if (canPay) setLoyaltyOpen(true); }
  function buyPlain() { setSyrupId('syrup_none'); setToppingId('topping_none'); if (canPay) setLoyaltyOpen(true); }
  function startPayment(customerPhone = null) { if (!canPay) return; setLoyaltyOpen(false); const intent = salesTerminalService.createPaymentIntent({ channelId: 'vending', methodId, orderPreview: preview, quote: pricing.quote }); setPayment({ ...intent, customerPhone }); setStep(1); setQrSeconds(QR_TTL_SECONDS); trackEvent('TerminalPaymentStarted', { channel_id: 'vending', payment_method: methodId, quote_id: pricing.quote.id, syrup_id: syrupId, topping_id: toppingId, loyalty_phone_provided: Boolean(customerPhone) }); }
  function continueWithPhone() { if (phoneDigits.length !== 10) return; startPayment(`+7${phoneDigits}`); }
  function confirmDemoPayment() { const confirmed = salesTerminalService.applyDemoPaymentConfirmation(payment); setPayment(confirmed); setStep(2); trackEvent('TerminalDemoPaymentConfirmed', { channel_id: 'vending', order_id: payment.orderId }); }
  function resetSale() { setPayment(null); setStep(0); setSelectionStage('base'); setSyrupId('syrup_none'); setToppingId('topping_none'); setMethodId('sbp'); setPhoneDigits(''); setQrSeconds(QR_TTL_SECONDS); setCancelOpen(false); refreshQuote(); }
  function cancelPurchase() { trackEvent('TerminalPurchaseCancelled', { machine_id: machineId, order_id: payment?.orderId || null, payment_method: methodId }); resetSale(); }
  function serviceTap() { const now = Date.now(); serviceClicks.current = [...serviceClicks.current.filter((value) => now - value < 1200), now]; if (serviceClicks.current.length >= 3) { serviceClicks.current = []; setServiceOpen(true); trackEvent('TerminalServiceGatewayOpened', { machine_id: machineId }); } }

  if (idle) return <IdleScreen onExit={exitIdle} />;
  return <main className="terminal-shell">
    <header className="terminal-header"><BrandMark /><button className="terminal-point" type="button" onClick={serviceTap}><span className="online-dot" />{machineId ? `Автомат ${machineId}` : 'Тестовый терминал'}</button></header><Stepper step={step} />
    {step === 0 && selectionStage === 'base' && <><PromotionPreStartBanner awareness={awareness} terminal /><TerminalPromotionHero pricing={pricing} /><div className="terminal-layout"><section className="terminal-main"><div className="terminal-title"><div><p className="terminal-kicker">Мягкое мороженое</p><h1>Выберите свой десерт</h1></div><span className="terminal-price">{serverPrice} ₽</span></div><PromotionPricePanel pricing={pricing} onRefresh={refreshQuote} /><div className="terminal-product"><ProductArtwork /><div><span className="terminal-pill">Базовый десерт</span><h2>{catalog.flavor.name.ru}</h2><p>Мягкое ванильное мороженое в фирменном стаканчике. Можно купить сразу или добавить сироп и посыпку.</p><div className="included-list"><span>✓ Мороженое</span><span>✓ Стаканчик</span></div></div></div><div className="terminal-config-actions terminal-base-actions"><button className="terminal-cta" type="button" onClick={buyPlain} disabled={!canPay}>Купить без добавок — {serverPrice} ₽</button><button className="terminal-secondary" type="button" onClick={() => setSelectionStage('syrup')}>Добавить сироп и посыпку →</button></div></section><aside className="terminal-summary"><div className="terminal-point-card"><p className="terminal-kicker">Точка продажи</p><strong>{machineId ? `Автомат № ${machineId}` : 'Тестовый терминал'}</strong><small>Тип точки определяется системой автоматически</small><span className="terminal-point-status"><span className="online-dot" /> Работает</span></div><div className="receipt"><p className="terminal-kicker">Ваш заказ</p><h3>{catalog.product.name.ru}</h3><div className="receipt-total"><span>К оплате</span><strong>{serverPrice} ₽</strong></div></div></aside></div></>}
    {step === 0 && selectionStage === 'syrup' && <section className="terminal-main terminal-config-screen"><div className="terminal-config-screen-head"><div><p className="terminal-kicker">Шаг 1 из 2</p><h1>Выберите сироп</h1></div><span className="terminal-price">{serverPrice} ₽</span></div><div className="choice-grid">{catalog.syrups.map((item) => <ChoiceCard active={syrupId === item.id} key={item.id} onClick={() => setSyrupId(item.id)}><span className={`flavor-swatch ${item.id}`} /><strong>{item.name.ru}</strong></ChoiceCard>)}</div><div className="terminal-config-actions"><button className="terminal-secondary" type="button" onClick={() => setSelectionStage('base')}>← Назад</button><button className="terminal-cta" type="button" onClick={() => setSelectionStage('topping')}>Дальше: посыпка →</button></div></section>}
    {step === 0 && selectionStage === 'topping' && <section className="terminal-main terminal-config-screen"><div className="terminal-config-screen-head"><div><p className="terminal-kicker">Шаг 2 из 2</p><h1>Добавьте посыпку</h1></div><span className="terminal-price">{serverPrice} ₽</span></div><div className="choice-grid">{catalog.toppings.map((item) => <ChoiceCard active={toppingId === item.id} key={item.id} onClick={() => setToppingId(item.id)}><span className={`topping-symbol ${item.id}`}>{item.id === 'topping_none' ? '—' : '✦'}</span><strong>{item.name.ru}</strong></ChoiceCard>)}</div><div className="terminal-config-actions"><button className="terminal-secondary" type="button" onClick={() => setSelectionStage('syrup')}>← Назад</button><button className="terminal-cta" type="button" onClick={() => setSelectionStage('summary')}>Проверить заказ →</button></div></section>}
    {step === 0 && selectionStage === 'summary' && <div className="terminal-layout"><section className="terminal-main"><div className="terminal-title"><div><p className="terminal-kicker">Проверьте заказ</p><h1>Всё готово</h1></div><span className="terminal-price">{serverPrice} ₽</span></div><div className="terminal-product"><ProductArtwork /><div><h2>{catalog.product.name.ru}</h2><p>Сироп: <strong>{syrup.name.ru}</strong></p><p>Посыпка: <strong>{topping.name.ru}</strong></p></div></div><div className="terminal-config-actions"><button className="terminal-secondary" type="button" onClick={() => setSelectionStage('syrup')}>Изменить состав</button><button className="terminal-cta" type="button" onClick={requestPayment} disabled={!canPay}>{pricing.status === 'loading' ? 'Проверяем цену…' : 'Перейти к оплате'} →</button></div></section><aside className="terminal-summary"><div className="receipt"><p className="terminal-kicker">Ваш заказ</p><h3>{catalog.product.name.ru}</h3><dl><dt>Сироп</dt><dd>{syrup.name.ru}</dd><dt>Посыпка</dt><dd>{topping.name.ru}</dd></dl><div className="receipt-total"><span>К оплате</span><strong>{serverPrice} ₽</strong></div></div><p className="safe-payment">Бонусы не являются обязательным условием покупки</p></aside></div>}
    {loyaltyOpen && <LoyaltyModal phoneDigits={phoneDigits} setPhoneDigits={setPhoneDigits} onContinue={continueWithPhone} onSkip={() => startPayment(null)} />}
    {step === 1 && <section className="payment-screen"><div className="payment-panel"><button className="terminal-back" type="button" onClick={() => { setPayment(null); setStep(0); setSelectionStage('summary'); }}>← Вернуться к заказу</button><p className="terminal-kicker">Заказ {payment.orderId}</p><h1>{payment.paymentRequired ? `Оплатите ${payment.amount} ₽` : 'Подарок готов к выдаче'}</h1><p>Оплатите по СБП или банковской картой через установленный POS-терминал.</p>{payment.paymentRequired && <><div className="payment-methods"><ChoiceCard active={methodId === 'sbp'} onClick={() => setMethodId('sbp')}><span className="method-icon">СБП</span><span><strong>СБП</strong><small>QR-код или банковское приложение</small></span></ChoiceCard><ChoiceCard active={methodId === 'yookassa_card'} onClick={() => setMethodId('yookassa_card')}><span className="method-icon">▣</span><span><strong>Банковская карта</strong><small>Оплата через POS-терминал</small></span></ChoiceCard></div>{methodId === 'sbp' ? <div className="payment-action"><QrPattern /><div><strong>Наведите камеру телефона</strong><p>QR действует ещё <b>{formatTimer(qrSeconds)}</b></p>{qrSeconds === 0 && <button className="terminal-secondary" type="button" onClick={() => setQrSeconds(QR_TTL_SECONDS)}>Обновить QR</button>}</div></div> : <div className="payment-action terminal-pos-action"><div className="method-icon">▣</div><div><strong>Оплата банковской картой</strong><p>Нажмите кнопку ниже, затем приложите или вставьте карту в POS-терминал.</p><button className="terminal-cta terminal-pos-pay" type="button" onClick={() => trackEvent('TerminalPosPaymentRequested', { machine_id: machineId, order_id: payment.orderId, amount: payment.amount })}>Оплатить картой — {payment.amount} ₽</button></div></div>}</>}<button className="demo-confirm" type="button" onClick={confirmDemoPayment}>Демо: подтвердить оплату</button><button className="terminal-cancel-purchase" type="button" onClick={() => setCancelOpen(true)}>Отказаться от покупки</button></div><aside className="payment-order-card"><ProductArtwork compact /><h2>{catalog.product.name.ru}</h2><p>Сироп: {syrup.name.ru}</p><p>Посыпка: {topping.name.ru}</p><strong>{payment.amount} ₽</strong></aside></section>}
    {step === 2 && <section className="success-screen"><div className="success-check">✓</div><p className="terminal-kicker">Оплата подтверждена</p><h1>Начинаем готовить!</h1><p>Заказ передан автомату. Заберите десерт после сигнала готовности.</p>{payment.customerPhone && <div className="terminal-saving">Покупка привязана к вашему номеру. Дальше с бонусами и отзывами работает Клуб Тимоши — аппарат ждать не нужно.</div>}<div className="sale-code"><span>Заказ</span><strong>{payment.orderId}</strong><span>Код выдачи</span><b>{payment.saleCode}</b></div><button className="terminal-cta compact" type="button" onClick={resetSale}>Новый заказ</button></section>}
    {cancelOpen && <div className="terminal-modal-backdrop"><section className="terminal-modal" role="alertdialog" aria-modal="true"><p className="terminal-kicker">Отмена покупки</p><h2>Отказаться от покупки?</h2><p>Текущая попытка оплаты будет прекращена. Мороженое не будет приготовлено.</p><div className="terminal-modal-actions"><button className="terminal-secondary" type="button" onClick={() => setCancelOpen(false)}>Нет, продолжить</button><button className="terminal-cancel-confirm" type="button" onClick={cancelPurchase}>Да, отказаться</button></div></section></div>}
    {serviceOpen && <div className="terminal-modal-backdrop"><section className="terminal-modal"><p className="terminal-kicker">Сервисный доступ</p><h2>Требуется авторизация</h2><p>Тройное нажатие открывает только защищённый шлюз. Выход в Android/Windows будет доступен после авторизации техника или мастера и проверки роли.</p><div className="terminal-modal-actions"><button className="terminal-secondary" type="button" onClick={() => setServiceOpen(false)}>Закрыть</button><button className="terminal-cta" type="button" disabled>Авторизация QR — следующий этап</button></div></section></div>}
  </main>;
}
