const crypto = require('crypto');

const CameraStatus = Object.freeze(Object.fromEntries(['ONLINE','OFFLINE','DEGRADED','AUTH_FAILED','STREAM_FAILED','STORAGE_FAILED','DISABLED','UNKNOWN'].map((v) => [v, v])));
const RecordingMode = Object.freeze(Object.fromEntries(['CONTINUOUS','MOTION','MACHINE_EVENT','HYBRID','LIVE_ONLY','DISABLED'].map((v) => [v, v])));
const SensorType = Object.freeze(Object.fromEntries(['PIR','CAMERA_ANALYTICS','RADAR','EXTERNAL','UNKNOWN'].map((v) => [v, v])));
const RecordingTriggerType = Object.freeze(Object.fromEntries(['MOTION_DETECTED','PERSON_AREA_ACTIVITY','PURCHASE_STARTED','PAYMENT_CONFIRMED','DISPENSE_FAILED','MACHINE_ERROR','SERVICE_DOOR_OPENED','OPERATOR_SERVICE_STARTED','TEST_DISPENSE_STARTED','IMPACT_DETECTED','TILT_DETECTED','CONNECTIVITY_LOST','MANUAL_REQUEST','INCIDENT_CREATED'].map((v) => [v, v])));
const IncidentType = Object.freeze(Object.fromEntries(['VANDALISM','DAMAGE','DISPENSE_DISPUTE','PAYMENT_DISPUTE','SAFETY','OPERATOR_ACTION','CONNECTIVITY','CAMERA_FAILURE','OTHER'].map((v) => [v, v])));
const VIDEO_EVENTS = Object.freeze(['CAMERA_REGISTERED','CAMERA_ONLINE','CAMERA_OFFLINE','CAMERA_STREAM_FAILED','MOTION_DETECTED','MOTION_CONFIRMED','VIDEO_RECORDING_STARTED','VIDEO_RECORDING_EXTENDED','VIDEO_RECORDING_COMPLETED','VIDEO_FRAGMENT_UPLOADED','VIDEO_FRAGMENT_DELETED','VIDEO_INCIDENT_CREATED','VIDEO_RETENTION_EXTENDED','VIDEO_LEGAL_HOLD_APPLIED','VIDEO_LEGAL_HOLD_RELEASED']);
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const date = (value) => value == null ? null : new Date(value);

class VideoCamera {
  constructor(value = {}) {
    Object.assign(this, {
      id: value.id || id('camera'), machineId: value.machineId, name: value.name || 'Камера автомата',
      model: value.model || null, serialNumber: value.serialNumber || null, locationDescription: value.locationDescription || null,
      streamProtocol: value.streamProtocol || 'RTSP', rtspUrlSecretRef: value.rtspUrlSecretRef || null,
      status: value.status || CameraStatus.UNKNOWN, recordingMode: value.recordingMode || RecordingMode.HYBRID,
      codec: value.codec || null, resolution: value.resolution || null, frameRate: value.frameRate || null,
      localStorageEnabled: value.localStorageEnabled !== false, localStorageCapacity: value.localStorageCapacity || 0,
      retentionHours: value.retentionHours ?? 72, preBufferSeconds: value.preBufferSeconds ?? 10,
      postBufferSeconds: value.postBufferSeconds ?? 20, lastFrameAt: date(value.lastFrameAt),
      lastHealthCheckAt: date(value.lastHealthCheckAt), source: value.source || 'MANUAL', metadata: value.metadata || {},
    });
  }
}
class CameraConnectionProfile { constructor(value = {}) { Object.assign(this, { id: value.id || id('connection'), cameraId: value.cameraId, protocol: value.protocol || 'RTSP', endpointSecretRef: value.endpointSecretRef, mediaProxyProfileRef: value.mediaProxyProfileRef || null, status: value.status || 'FOUNDATION_ONLY', metadata: value.metadata || {} }); } }
class MotionSensor { constructor(value = {}) { Object.assign(this, { id: value.id || id('sensor'), machineId: value.machineId, cameraId: value.cameraId || null, sensorType: value.sensorType || SensorType.UNKNOWN, status: value.status || 'UNKNOWN', sensitivity: value.sensitivity ?? 0.5, cooldownSeconds: value.cooldownSeconds ?? 15, lastMotionAt: date(value.lastMotionAt), enabled: value.enabled !== false, source: value.source || 'MANUAL', metadata: value.metadata || {} }); } }
class VideoRecordingPolicy { constructor(value = {}) { Object.assign(this, { id: value.id || id('policy'), cameraId: value.cameraId, preBufferSeconds: value.preBufferSeconds ?? 10, postBufferSeconds: value.postBufferSeconds ?? 20, maximumRecordingSeconds: value.maximumRecordingSeconds ?? 300, extendOnMotion: value.extendOnMotion !== false, extendOnMachineEvent: value.extendOnMachineEvent !== false, zones: (value.zones || []).map((z) => ({ zoneId: z.zoneId, name: z.name, polygon: z.polygon || [], enabled: z.enabled !== false, sensitivity: z.sensitivity ?? 0.5, triggerRecording: z.triggerRecording !== false })) }); } }
class VideoRecordingSession { constructor(value = {}) { Object.assign(this, { id: value.id || id('recording'), machineId: value.machineId, cameraId: value.cameraId, status: value.status || 'RECORDING', startedAt: date(value.startedAt) || new Date(), plannedEndAt: date(value.plannedEndAt), endedAt: date(value.endedAt), triggerType: value.triggerType, triggerEventId: value.triggerEventId || null, preBufferSeconds: value.preBufferSeconds || 0, postBufferSeconds: value.postBufferSeconds || 0, maximumRecordingSeconds: value.maximumRecordingSeconds || 300, extensions: value.extensions || 0, metadata: value.metadata || {} }); } }
class VideoFragment { constructor(value = {}) { Object.assign(this, { id: value.id || id('fragment'), machineId: value.machineId, cameraId: value.cameraId, recordingSessionId: value.recordingSessionId, startedAt: date(value.startedAt), endedAt: date(value.endedAt), durationSeconds: value.durationSeconds || 0, triggerType: value.triggerType, triggerEventId: value.triggerEventId || null, orderId: value.orderId || null, paymentId: value.paymentId || null, maintenanceSessionId: value.maintenanceSessionId || null, incidentId: value.incidentId || null, storageLocation: value.storageLocation || null, localOnly: value.localOnly !== false, uploaded: value.uploaded === true, checksum: value.checksum || null, sizeBytes: value.sizeBytes || 0, retentionUntil: date(value.retentionUntil), legalHold: value.legalHold === true, createdAt: date(value.createdAt) || new Date(), metadata: value.metadata || {} }); } }
class VideoIncident { constructor(value = {}) { Object.assign(this, { id: value.id || id('incident'), machineId: value.machineId, title: value.title, description: value.description || '', type: value.type || IncidentType.OTHER, severity: value.severity || 'MEDIUM', status: value.status || 'OPEN', openedAt: date(value.openedAt) || new Date(), closedAt: date(value.closedAt), openedBy: value.openedBy, assignedTo: value.assignedTo || null, retentionReason: value.retentionReason || null, metadata: value.metadata || {} }); } }
class VideoIncidentLink { constructor(value = {}) { Object.assign(this, { id: value.id || id('incident_link'), incidentId: value.incidentId, fragmentId: value.fragmentId, linkedAt: date(value.linkedAt) || new Date(), linkedBy: value.linkedBy }); } }
class VideoRetentionPolicy { constructor(value = {}) { Object.assign(this, { id: value.id || id('retention'), machineId: value.machineId || null, cameraId: value.cameraId || null, retentionHours: value.retentionHours ?? 72, automaticDeletionEnabled: value.automaticDeletionEnabled !== false, metadata: value.metadata || {} }); } }
class CameraHealthSnapshot { constructor(value = {}) { Object.assign(this, { id: value.id || id('camera_health'), cameraId: value.cameraId, checkedAt: date(value.checkedAt) || new Date(), networkReachable: !!value.networkReachable, rtspPortReachable: !!value.rtspPortReachable, authorizationSuccessful: !!value.authorizationSuccessful, framesReceived: !!value.framesReceived, imageFrozen: !!value.imageFrozen, cameraTimeSynchronized: !!value.cameraTimeSynchronized, localStorageAvailable: !!value.localStorageAvailable, sufficientFreeSpace: !!value.sufficientFreeSpace, status: value.status || CameraStatus.UNKNOWN, details: value.details || {} }); } }
class VideoAccessAudit { constructor(value = {}) { Object.assign(this, { id: value.id || id('video_audit'), action: value.action, actorId: value.actorId, roles: value.roles || [], machineId: value.machineId || null, cameraId: value.cameraId || null, fragmentId: value.fragmentId || null, incidentId: value.incidentId || null, outcome: value.outcome || 'SUCCESS', reason: value.reason || null, occurredAt: date(value.occurredAt) || new Date(), metadata: value.metadata || {} }); } }

module.exports = { CameraStatus, RecordingMode, SensorType, RecordingTriggerType, IncidentType, VIDEO_EVENTS, VideoCamera, CameraConnectionProfile, MotionSensor, VideoRecordingPolicy, VideoRecordingSession, VideoFragment, VideoIncident, VideoIncidentLink, VideoRetentionPolicy, CameraHealthSnapshot, VideoAccessAudit };
