const { ApiError } = require('../../platform/errors/ApiError');
const { CameraStatus, RecordingMode, RecordingTriggerType, VideoCamera, MotionSensor, VideoRecordingPolicy, VideoRecordingSession, VideoFragment, VideoIncident, VideoIncidentLink, CameraHealthSnapshot, VideoAccessAudit } = require('./VideoSurveillanceModels');

const ALLOWED = new Set(['PLATFORM_OWNER','ADMIN','SECURITY_OFFICER']);
const EVENT_TRIGGER = { PAYMENT_CONFIRMED_FOR_MACHINE: 'PAYMENT_CONFIRMED', MACHINE_RUNTIME_ERROR_ENTERED: 'MACHINE_ERROR', MACHINE_CYCLE_COMPLETED: 'PURCHASE_STARTED', MACHINE_MAINTENANCE_STARTED: 'OPERATOR_SERVICE_STARTED', MACHINE_DISCONNECTED: 'CONNECTIVITY_LOST' };
class VideoSurveillanceService {
  constructor({ repository, cameraAdapter, recorderAdapter, storageAdapter, eventPublisher, clock = () => new Date() }) { Object.assign(this, { repository, cameraAdapter, recorderAdapter, storageAdapter, eventPublisher, clock }); }
  authorize(ctx, permission) {
    const roles = ctx?.roles || []; if (!roles.some((r) => ALLOWED.has(r))) throw new ApiError({ statusCode: 403, code: 'VIDEO_ACCESS_DENIED', message: 'Доступ к видеонаблюдению запрещён.' });
    if (permission === 'LEGAL_HOLD' && !roles.includes('PLATFORM_OWNER') && !(roles.includes('ADMIN') && (ctx.permissions || []).includes('video:legal_hold'))) throw new ApiError({ statusCode: 403, code: 'VIDEO_LEGAL_HOLD_DENIED', message: 'Недостаточно прав для legal hold.' });
  }
  async publish(eventType, aggregateType, aggregateId, payload, ctx = {}) { return this.eventPublisher?.publish({ eventType, aggregateType, aggregateId, actorType: 'USER', actorId: ctx.actorId || 'video-runtime', sourceChannel: 'VIDEO_SURVEILLANCE', correlationId: ctx.correlationId || aggregateId, payload }); }
  audit(action, refs, ctx, outcome = 'SUCCESS', reason = null) { return this.repository.addAudit(new VideoAccessAudit({ action, ...refs, actorId: ctx?.actorId || 'video-runtime', roles: ctx?.roles || [], outcome, reason })); }
  sanitizeCamera(camera) { if (!camera) return null; const { rtspUrlSecretRef, ...safe } = camera; return { ...safe, secretConfigured: !!rtspUrlSecretRef, liveView: { status: 'FOUNDATION_ONLY', transport: 'MEDIA_PROXY', url: null } }; }
  listCameras(machineId, ctx) { this.authorize(ctx); return this.repository.listCameras(machineId).map((v) => this.summary(v)); }
  getCamera(machineId, cameraId, ctx) { this.authorize(ctx); const camera = this.repository.getCamera(cameraId); if (!camera || camera.machineId !== machineId) throw new ApiError({ statusCode: 404, code: 'CAMERA_NOT_FOUND', message: 'Камера не найдена.' }); return this.summary(camera); }
  summary(camera) { return { ...this.sanitizeCamera(camera), sensors: this.repository.listSensors(camera.machineId, camera.id), health: this.repository.latestHealth(camera.id), activeIncidentCount: this.repository.listIncidents(camera.machineId).filter((v) => v.status !== 'CLOSED').length, fragmentCount: this.repository.listFragments(camera.machineId).filter((v) => v.cameraId === camera.id).length }; }
  async registerCamera(machineId, input, ctx) { this.authorize(ctx); if (!input.rtspUrlSecretRef) throw new ApiError({ statusCode: 400, code: 'CAMERA_SECRET_REFERENCE_REQUIRED', message: 'Требуется ссылка на секрет подключения.' }); const camera = this.repository.saveCamera(new VideoCamera({ ...input, machineId })); this.repository.savePolicy(new VideoRecordingPolicy({ ...input, cameraId: camera.id })); await this.publish('CAMERA_REGISTERED', 'VideoCamera', camera.id, { machineId }, ctx); this.audit('CAMERA_SETTINGS_CHANGED', { machineId, cameraId: camera.id }, ctx); return this.sanitizeCamera(camera); }
  async updateCamera(machineId, cameraId, input, ctx) { const existing = this.getRaw(machineId, cameraId, ctx); const updated = this.repository.saveCamera(new VideoCamera({ ...existing, ...input, id: cameraId, machineId, rtspUrlSecretRef: input.rtspUrlSecretRef || existing.rtspUrlSecretRef })); if (input.zones || input.maximumRecordingSeconds) this.repository.savePolicy(new VideoRecordingPolicy({ ...this.repository.getPolicy(cameraId), ...input, cameraId })); this.audit('CAMERA_SETTINGS_CHANGED', { machineId, cameraId }, ctx); return this.sanitizeCamera(updated); }
  getRaw(machineId, cameraId, ctx) { this.authorize(ctx); const camera = this.repository.getCamera(cameraId); if (!camera || camera.machineId !== machineId) throw new ApiError({ statusCode: 404, code: 'CAMERA_NOT_FOUND', message: 'Камера не найдена.' }); return camera; }
  async check(machineId, cameraId, ctx) { const camera = this.getRaw(machineId, cameraId, ctx); const result = await this.cameraAdapter.healthCheck(camera); let status = CameraStatus.ONLINE; if (!result.networkReachable || !result.rtspPortReachable) status = CameraStatus.OFFLINE; else if (!result.authorizationSuccessful) status = CameraStatus.AUTH_FAILED; else if (!result.framesReceived || result.imageFrozen) status = CameraStatus.STREAM_FAILED; else if (!result.localStorageAvailable || !result.sufficientFreeSpace) status = CameraStatus.STORAGE_FAILED; else if (!result.cameraTimeSynchronized) status = CameraStatus.DEGRADED; const snapshot = this.repository.addHealth(new CameraHealthSnapshot({ cameraId, ...result, status })); camera.status = status; camera.lastHealthCheckAt = snapshot.checkedAt; if (result.framesReceived) camera.lastFrameAt = snapshot.checkedAt; this.repository.saveCamera(camera); await this.publish(status === CameraStatus.ONLINE ? 'CAMERA_ONLINE' : status === CameraStatus.STREAM_FAILED ? 'CAMERA_STREAM_FAILED' : 'CAMERA_OFFLINE', 'VideoCamera', cameraId, { machineId, status }, ctx); return snapshot; }
  async motion(sensorId, input = {}, ctx = {}) { const sensor = this.repository.sensors.get(sensorId); if (!sensor || !sensor.enabled) return { ignored: true }; const now = this.clock(); const prior = sensor.lastMotionAt; sensor.lastMotionAt = now; this.repository.saveSensor(sensor); const camera = this.repository.getCamera(sensor.cameraId); if (sensor.sensorType === 'PIR') { await this.cameraAdapter.wake(camera); await this.publish('MOTION_DETECTED','MotionSensor',sensor.id,{ machineId: sensor.machineId, cameraId: sensor.cameraId, confirmed: false },ctx); return { awakened: true, confirmed: false, cooldown: !!prior && (now - prior) / 1000 < sensor.cooldownSeconds }; } return this.confirmMotion(camera, input, ctx); }
  async confirmMotion(camera, input = {}, ctx = {}) { if (!camera) return { confirmed: false }; const policy = this.repository.getPolicy(camera.id); const zone = policy?.zones.find((z) => z.zoneId === input.zoneId); if (zone && (!zone.enabled || !zone.triggerRecording)) return { confirmed: false }; await this.publish('MOTION_CONFIRMED','VideoCamera',camera.id,{ machineId: camera.machineId, zoneId: input.zoneId || null },ctx); if ([RecordingMode.MOTION, RecordingMode.HYBRID].includes(camera.recordingMode)) return { confirmed: true, session: await this.startOrExtend(camera, 'MOTION_DETECTED', input.eventId, ctx) }; return { confirmed: true, session: null }; }
  async startOrExtend(camera, triggerType, triggerEventId, ctx = {}) { const policy = this.repository.getPolicy(camera.id) || new VideoRecordingPolicy({ cameraId: camera.id, ...camera }); const now = this.clock(); const active = this.repository.activeSession(camera.id); if (active) { const cap = new Date(active.startedAt.getTime() + policy.maximumRecordingSeconds * 1000); active.plannedEndAt = new Date(Math.min(cap.getTime(), now.getTime() + policy.postBufferSeconds * 1000)); active.extensions += 1; this.repository.saveSession(active); await this.recorderAdapter.extend(active); await this.publish('VIDEO_RECORDING_EXTENDED','VideoRecordingSession',active.id,{ machineId: camera.machineId, cameraId: camera.id, triggerType },ctx); return active; } const session = new VideoRecordingSession({ machineId: camera.machineId, cameraId: camera.id, triggerType, triggerEventId, startedAt: new Date(now.getTime() - policy.preBufferSeconds * 1000), plannedEndAt: new Date(now.getTime() + policy.postBufferSeconds * 1000), preBufferSeconds: policy.preBufferSeconds, postBufferSeconds: policy.postBufferSeconds, maximumRecordingSeconds: policy.maximumRecordingSeconds }); this.repository.saveSession(session); await this.recorderAdapter.start(session); await this.publish('VIDEO_RECORDING_STARTED','VideoRecordingSession',session.id,{ machineId: camera.machineId, cameraId: camera.id, triggerType },ctx); return session; }
  async complete(sessionId, ctx = {}) { const session = this.repository.sessions.get(sessionId); if (!session) return null; session.status = 'COMPLETED'; session.endedAt = this.clock(); this.repository.saveSession(session); await this.recorderAdapter.stop(session); const camera = this.repository.getCamera(session.cameraId); const fragment = new VideoFragment({ machineId: session.machineId, cameraId: session.cameraId, recordingSessionId: session.id, startedAt: session.startedAt, endedAt: session.endedAt, durationSeconds: Math.max(0, (session.endedAt - session.startedAt) / 1000), triggerType: session.triggerType, triggerEventId: session.triggerEventId, retentionUntil: new Date(session.endedAt.getTime() + (camera.retentionHours || 72) * 3600000) }); const stored = await this.storageAdapter.saveMetadata(fragment); Object.assign(fragment, stored); this.repository.saveFragment(fragment); await this.publish('VIDEO_RECORDING_COMPLETED','VideoRecordingSession',session.id,{ machineId: session.machineId, fragmentId: fragment.id },ctx); return fragment; }
  handlePlatformEvent(event) { const trigger = EVENT_TRIGGER[event.eventType]; if (!trigger) return null; const machineId = event.payload.machineId || event.aggregateId; return Promise.all(this.repository.listCameras(machineId).filter((c) => [RecordingMode.MACHINE_EVENT, RecordingMode.HYBRID].includes(c.recordingMode)).map((c) => this.startOrExtend(c, trigger, event.eventId, { actorId: 'platform-event-bus', correlationId: event.correlationId }))); }
  subscriber() { return { subscriberId: 'video-surveillance-runtime-v1', handler: (event) => this.handlePlatformEvent(event) }; }
  listFragments(machineId, ctx) { this.authorize(ctx); this.audit('ARCHIVE_VIEWED',{ machineId },ctx); return this.repository.listFragments(machineId); }
  listIncidents(machineId, ctx) { this.authorize(ctx); return this.repository.listIncidents(machineId); }
  getIncident(id, ctx) { this.authorize(ctx); const value = this.repository.getIncident(id); if (!value) throw new ApiError({ statusCode: 404, code: 'VIDEO_INCIDENT_NOT_FOUND', message: 'Инцидент не найден.' }); return value; }
  async createIncident(input, ctx) { this.authorize(ctx); const incident = this.repository.saveIncident(new VideoIncident({ ...input, openedBy: ctx.actorId })); for (const fragmentId of input.fragmentIds || []) { const fragment = this.repository.getFragment(fragmentId); if (fragment) { fragment.incidentId = incident.id; this.repository.saveFragment(fragment); this.repository.saveLink(new VideoIncidentLink({ incidentId: incident.id, fragmentId, linkedBy: ctx.actorId })); } } await this.publish('VIDEO_INCIDENT_CREATED','VideoIncident',incident.id,{ machineId: incident.machineId },ctx); this.audit('INCIDENT_CREATED',{ machineId: incident.machineId, incidentId: incident.id },ctx); return incident; }
  updateIncident(id, input, ctx) { const incident = this.getIncident(id, ctx); Object.assign(incident, input); if (input.status === 'CLOSED' && !incident.closedAt) incident.closedAt = this.clock(); return this.repository.saveIncident(incident); }
  async legalHold(fragmentId, enabled, reason, ctx) { this.authorize(ctx, 'LEGAL_HOLD'); const fragment = this.repository.getFragment(fragmentId); if (!fragment) throw new ApiError({ statusCode: 404, code: 'VIDEO_FRAGMENT_NOT_FOUND', message: 'Фрагмент не найден.' }); fragment.legalHold = enabled; fragment.metadata = { ...fragment.metadata, legalHoldReason: reason || null }; this.repository.saveFragment(fragment); this.audit(enabled ? 'LEGAL_HOLD_APPLIED' : 'LEGAL_HOLD_RELEASED',{ machineId: fragment.machineId, cameraId: fragment.cameraId, fragmentId },ctx); await this.publish(enabled ? 'VIDEO_LEGAL_HOLD_APPLIED' : 'VIDEO_LEGAL_HOLD_RELEASED','VideoFragment',fragmentId,{ machineId: fragment.machineId, reason },ctx); return fragment; }
  async extendRetention(fragmentId, hours, reason, ctx) { this.authorize(ctx); const fragment = this.repository.getFragment(fragmentId); if (!fragment) throw new ApiError({ statusCode: 404, code: 'VIDEO_FRAGMENT_NOT_FOUND', message: 'Фрагмент не найден.' }); fragment.retentionUntil = new Date(Math.max(fragment.retentionUntil?.getTime() || 0, this.clock().getTime()) + hours * 3600000); this.repository.saveFragment(fragment); this.audit('RETENTION_EXTENDED',{ machineId: fragment.machineId, fragmentId },ctx,'SUCCESS',reason); await this.publish('VIDEO_RETENTION_EXTENDED','VideoFragment',fragmentId,{ machineId: fragment.machineId, hours, reason },ctx); return fragment; }
  async purgeExpired(ctx = { actorId: 'retention-worker' }) { const deleted = []; for (const fragment of this.repository.listFragments()) if (!fragment.legalHold && fragment.retentionUntil <= this.clock()) { const result = await this.storageAdapter.delete(fragment); this.repository.deleteFragment(fragment.id); this.audit('FRAGMENT_DELETED',{ machineId: fragment.machineId, cameraId: fragment.cameraId, fragmentId: fragment.id },ctx,result.deleted === false ? 'NOT_FOUND' : 'SUCCESS'); await this.publish('VIDEO_FRAGMENT_DELETED','VideoFragment',fragment.id,{ machineId: fragment.machineId, storageResult: result.deleted },ctx); deleted.push(fragment.id); } return deleted; }
  auditLog(ctx) { this.authorize(ctx); return this.repository.listAudit(); }
}
module.exports = { VideoSurveillanceService, EVENT_TRIGGER };
