const test = require('node:test'); const assert = require('node:assert/strict');
const { GiftTransferRepository, GiftTransferService, NotificationOrchestrator, NotificationChannelAdapter } = require('../src/modules/gift_transfer');
class Adapter extends NotificationChannelAdapter { constructor(channel,status){super(channel);this.status=status} async send(){return{status:this.status,providerMessageId:`${this.channel}-1`}} }
function fixture({ registered = true } = {}) { const now = new Date('2026-08-14T10:00:00Z'); const orders=new Map([['order-1',{id:'order-1',customerId:'sender',status:'PAID',paymentStatus:'paid',amount:150,currency:'RUB',machineId:'machine-1',expiresAt:new Date('2026-08-15T10:00:00Z')}]]); const customers=new Map([['sender',{id:'sender',name:'Александр',phone:'+79990000001',phoneVerified:true}],...(registered?[['recipient',{id:'recipient',phone:'+79990000002',phoneVerified:true}]]:[])]); const repository=new GiftTransferRepository(); const credits=[]; const events=[];
  const orderRepository={findByIdForCustomer:async(id,cid)=>orders.get(id)?.customerId===cid?orders.get(id):null,findById:async id=>orders.get(id),cancelPrepaidToBalance:async(id,at)=>Object.assign(orders.get(id),{status:'CANCELLED_BY_CUSTOMER',cancelledToBalanceAt:at,bonusEarned:0}),reserveForGift:async id=>orders.get(id)?.status==='PAID'?Object.assign(orders.get(id),{status:'GIFT_TRANSFERRED',bonusEarned:0}):null,releaseGift:async id=>Object.assign(orders.get(id),{status:'PAID'}),completeGift:async id=>orders.get(id)?.status==='GIFT_TRANSFERRED'?Object.assign(orders.get(id),{status:'COMPLETED'}):null};
  const service=new GiftTransferService({repository,clock:()=>now,tokenFactory:()=> 'safe-one-time-token',orderRepository,customerRepository:{findById:async id=>customers.get(id),findByVerifiedPhone:async phone=>[...customers.values()].find(x=>x.phone===phone&&x.phoneVerified)||null},clubAccountRuntime:{creditOrderReturn:async(cid,order,ctx)=>{if(!credits.some(x=>x.key===ctx.idempotencyKey))credits.push({key:ctx.idempotencyKey,amount:order.amount});return{transaction:{id:`tx-${order.id}`}}}},notificationOrchestrator:new NotificationOrchestrator({repository,clock:()=>now,adapters:[new Adapter('TELEGRAM','SENT'),new Adapter('MAX','SENT')]}),eventPublisher:{publish:async e=>(events.push(e),e)}}); return {service,repository,orders,customers,credits,events,now}; }
test('отказ возвращает стоимость один раз и закрывает заказ без бонусов',async()=>{const f=fixture();const first=await f.service.cancelPrepaidOrderToBalance('sender','order-1',{correlationId:'corr'});const second=await f.service.cancelPrepaidOrderToBalance('sender','order-1',{correlationId:'corr'});assert.equal(first.changed,true);assert.equal(second.changed,false);assert.equal(f.credits.length,1);assert.equal(f.orders.get('order-1').status,'CANCELLED_BY_CUSTOMER')});
test('подарок существующему клиенту создаёт одну передачу и две доставки',async()=>{const f=fixture();const result=await f.service.createGift('sender','order-1',{recipientPhone:'+7 (999) 000-00-02'},{correlationId:'corr-gift'});assert.equal(result.giftTransfer.status,'AVAILABLE');assert.equal(result.deliveries.length,2);assert.deepEqual(result.deliveries.map(x=>x.channel),['TELEGRAM','MAX']);assert.equal(f.repository.list().length,1);await assert.rejects(()=>f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'}),/передача уже создавалась/)});
test('нельзя подарить самому себе',async()=>{const f=fixture();await assert.rejects(()=>f.service.createGift('sender','order-1',{recipientPhone:'+79990000001'}),/Нельзя подарить заказ самому себе/)});
test('незарегистрированный получатель не создаётся автоматически и claim требует подтверждённый телефон',async()=>{const f=fixture({registered:false});const created=await f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});assert.equal(created.giftTransfer.recipientCustomerId,null);assert.equal(created.giftTransfer.status,'WAITING_FOR_REGISTRATION');f.customers.set('wrong',{id:'wrong',phone:'+79990000003',phoneVerified:true});await assert.rejects(()=>f.service.claimInvitation('wrong','safe-one-time-token'),/подтверждённого номера/);f.customers.set('recipient',{id:'recipient',phone:'+79990000002',phoneVerified:true});const claimed=await f.service.claimInvitation('recipient','safe-one-time-token');assert.equal(claimed.status,'AVAILABLE');await assert.rejects(()=>f.service.claimInvitation('recipient','safe-one-time-token'),/уже использовано/)});
test('принятие, FOUNDATION_ONLY-контракт, одноразовая выдача и отсутствие бонусов',async()=>{const f=fixture();const {giftTransfer}=await f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});assert.equal(f.orders.get('order-1').status,'GIFT_TRANSFERRED');await f.service.accept('recipient',giftTransfer.id);const redemption=await f.service.requestRedemption('recipient',giftTransfer.id);assert.equal((new Date(redemption.expiresAt)-new Date(redemption.issuedAt))/60000,5);assert.deepEqual({giftId:redemption.machineContract.giftId,orderId:redemption.machineContract.orderId,recipientCustomerId:redemption.machineContract.recipientCustomerId,machineId:redemption.machineContract.machineId,singleUse:redemption.machineContract.singleUse,status:redemption.machineContract.status},{giftId:giftTransfer.id,orderId:'order-1',recipientCustomerId:'recipient',machineId:'machine-1',singleUse:true,status:'FOUNDATION_ONLY'});await assert.rejects(()=>f.service.redeem(giftTransfer.id,redemption.code),/не подтверждена/);const done=await f.service.redeem(giftTransfer.id,redemption.code,{dispenseResult:'SUCCESS',machineId:'machine-1'});assert.equal(done.status,'REDEEMED');assert.equal(f.orders.get('order-1').status,'COMPLETED');await assert.rejects(()=>f.service.redeem(giftTransfer.id,redemption.code,{dispenseResult:'SUCCESS'}),/уже использован/);assert.equal(f.credits.length,0)});
test('просроченный подарок нельзя принять, право возвращается отправителю',async()=>{const f=fixture();const {giftTransfer}=await f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});f.repository.findById(giftTransfer.id).expiresAt=new Date('2026-08-14T09:59:00Z');await assert.rejects(()=>f.service.accept('recipient',giftTransfer.id),(error)=>error.code==='GIFT_EXPIRED');assert.equal(f.repository.findById(giftTransfer.id).status,'RETURNED_TO_SENDER');assert.equal(f.credits.length,1);assert.equal(f.orders.get('order-1').status,'CANCELLED_BY_CUSTOMER')});
test('отмена до принятия разрешена, после принятия запрещена',async()=>{const f=fixture();const a=await f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});assert.equal((await f.service.cancel('sender',a.giftTransfer.id)).status,'CANCELLED');const g=fixture();const b=await g.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});await g.service.accept('recipient',b.giftTransfer.id);await assert.rejects(()=>g.service.cancel('sender',b.giftTransfer.id),/После принятия/)});
test('истечение идемпотентно возвращает деньги исходному покупателю',async()=>{const f=fixture();const {giftTransfer}=await f.service.createGift('sender','order-1',{recipientPhone:'+79990000002'});await f.service.expire(giftTransfer.id);await f.service.expire(giftTransfer.id);assert.equal(f.credits.length,1);assert.equal(f.repository.findById(giftTransfer.id).status,'RETURNED_TO_SENDER');assert.equal(f.orders.get('order-1').status,'CANCELLED_BY_CUSTOMER')});
test('сбой одного канала не влияет на успешный второй канал',async()=>{const repository=new GiftTransferRepository();const orchestrator=new NotificationOrchestrator({repository,adapters:[new Adapter('TELEGRAM','FAILED'),new Adapter('MAX','SENT')]});const rows=await orchestrator.send({id:'n1',channels:['TELEGRAM','MAX'],correlationId:'c'});assert.deepEqual(rows.map(x=>x.status),['FAILED','SENT']);assert.equal(repository.listDeliveries('n1').length,2)});
