const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('crypto');
const { PrismaClient } = require('@prisma/client');
const { PostgresInventoryReservationService } = require('../src/modules/inventory');

const enabled = Boolean(process.env.DATABASE_URL); const pg = enabled ? test : test.skip; const prisma = enabled ? new PrismaClient() : null;
const ids = () => { const suffix = crypto.randomUUID(); return { organizationId: `org_${suffix}`, machineId: `machine_${suffix}`, locationId: `location_${suffix}` }; };
async function fixture({ quantity = 1, itemCount = 1, clock } = {}) {
  const scope = ids();
  await prisma.inventoryRuntimeLocation.create({ data: { id: scope.locationId, code: scope.locationId, name: 'Тестовый автомат', locationType: 'MACHINE', machineId: scope.machineId } });
  const items = [];
  for (let index = 0; index < itemCount; index++) {
    const item = await prisma.inventoryRuntimeItem.create({ data: { id: `item_${crypto.randomUUID()}`, sku: `sku_${crypto.randomUUID()}`, name: `Позиция ${index}`, category: index ? 'INGREDIENT' : 'CONSUMABLE', baseUnit: 'portion' } });
    await prisma.inventoryRuntimeStock.create({ data: { ...scope, inventoryItemId: item.id, physicalQuantity: quantity } }); items.push(item);
  }
  const service = new PostgresInventoryReservationService({ prisma, ...(clock && { clock }) });
  return { scope, items, service };
}
function command(f, key, extra = {}) { return { request: { ...f.scope, saleFlowId: `flow_${key}`, orderId: `order_${key}`, operationType: 'CUSTOMER_SALE', items: f.items.map((item) => ({ inventoryItemId: item.id, ingredientType: item.category, quantity: 1, unit: 'portion' })), ...extra }, context: { ...f.scope, actorType: 'SYSTEM', actorId: 'test', correlationId: `corr_${key}`, idempotencyKey: key } }; }
test.after(async () => { if (prisma) await prisma.$disconnect(); });

pg('reserve success is durable, tenant and machine scoped, and creates outbox atomically', async () => { const f = await fixture(); const c = command(f, `reserve_${crypto.randomUUID()}`); const result = await f.service.reserve(c.request, c.context); assert.equal(result.reservation.status, 'RESERVED'); assert.equal(result.reservation.items.length, 1); assert.equal((await prisma.inventoryRuntimeStock.findFirst({ where: f.scope })).activeReservedQuantity, 1); assert.equal(await prisma.transactionalOutboxEvent.count({ where: { aggregateId: result.reservation.reservationId, eventType: 'INVENTORY_RESERVED' } }), 1); const restarted = new PostgresInventoryReservationService({ prisma }); const replay = await restarted.reserve(c.request, c.context); assert.equal(replay.idempotentReplay, true); assert.equal(replay.reservation.reservationId, result.reservation.reservationId); });

pg('two concurrent reservations of the last unit produce one RESERVED and one FAILED', async () => { const f = await fixture(); const a = command(f, `last_a_${crypto.randomUUID()}`); const b = command(f, `last_b_${crypto.randomUUID()}`); const results = await Promise.all([f.service.reserve(a.request, a.context), f.service.reserve(b.request, b.context)]); assert.deepEqual(results.map((x) => x.reservation.status).sort(), ['FAILED','RESERVED']); const stock = await prisma.inventoryRuntimeStock.findFirst({ where: f.scope }); assert.equal(stock.activeReservedQuantity, 1); assert.ok(stock.activeReservedQuantity <= stock.physicalQuantity); });

pg('stress: exactly physical stock reservations succeed without over-reservation', async () => { const f = await fixture({ quantity: 10 }); const results = await Promise.all(Array.from({ length: 50 }, (_, index) => { const c = command(f, `stress_${index}_${crypto.randomUUID()}`); return f.service.reserve(c.request, c.context); })); assert.equal(results.filter((x) => x.reservation.status === 'RESERVED').length, 10); assert.equal(results.filter((x) => x.reservation.status === 'FAILED').length, 40); const stock = await prisma.inventoryRuntimeStock.findFirst({ where: f.scope }); assert.equal(stock.activeReservedQuantity, 10); assert.equal(stock.physicalQuantity, 10); });

pg('stress: five independent 50-way runs reserve exactly ten units each', async () => { for (let run = 0; run < 5; run++) { const f = await fixture({ quantity: 10 }); const results = await Promise.all(Array.from({ length: 50 }, (_, index) => { const c = command(f, `stress5_${run}_${index}_${crypto.randomUUID()}`); return f.service.reserve(c.request, c.context); })); assert.equal(results.filter((x) => x.reservation.status === 'RESERVED').length, 10); assert.equal(results.filter((x) => x.reservation.status === 'FAILED').length, 40); const stock = await prisma.inventoryRuntimeStock.findFirst({ where: f.scope }); assert.deepEqual([stock.physicalQuantity, stock.activeReservedQuantity], [10, 10]); } });

pg('multi-item reserve is all-or-nothing when one item is unavailable', async () => { const f = await fixture({ quantity: 10, itemCount: 3 }); await prisma.inventoryRuntimeStock.update({ where: { organizationId_machineId_locationId_inventoryItemId: { ...f.scope, inventoryItemId: f.items[2].id } }, data: { physicalQuantity: 0 } }); const c = command(f, `multi_${crypto.randomUUID()}`); const result = await f.service.reserve(c.request, c.context); assert.equal(result.reservation.status, 'FAILED'); const stocks = await prisma.inventoryRuntimeStock.findMany({ where: f.scope, orderBy: { inventoryItemId: 'asc' } }); assert.ok(stocks.every((stock) => stock.activeReservedQuantity === 0)); });

pg('consume/release and expire/consume races perform one terminal stock mutation', async () => { for (const pair of [['consume','release'],['expire','consume']]) { const f = await fixture(); const c = command(f, `race_${pair.join('_')}_${crypto.randomUUID()}`, pair[0] === 'expire' ? { expiresAt: new Date(Date.now() + 60000) } : {}); const held = await f.service.reserve(c.request, c.context); const calls = pair.map((action) => f.service[action](held.reservation.reservationId, {}, { organizationId: f.scope.organizationId, idempotencyKey: `${action}_${crypto.randomUUID()}` })); const settled = await Promise.allSettled(calls); assert.equal(settled.filter((x) => x.status === 'fulfilled').length, 1); const stock = await prisma.inventoryRuntimeStock.findFirst({ where: f.scope }); assert.ok(stock.activeReservedQuantity === 0 && stock.physicalQuantity >= 0); } });

pg('concurrent consume and concurrent release are persistent idempotent terminal transitions', async () => { for (const action of ['consume','release']) { const f = await fixture(); const c = command(f, `same_${action}_${crypto.randomUUID()}`); const held = await f.service.reserve(c.request, c.context); const results = await Promise.all([f.service[action](held.reservation.reservationId, {}, { organizationId: f.scope.organizationId, idempotencyKey: `${action}_a_${crypto.randomUUID()}` }), f.service[action](held.reservation.reservationId, {}, { organizationId: f.scope.organizationId, idempotencyKey: `${action}_b_${crypto.randomUUID()}` })]); assert.equal(results.filter((x) => x.idempotentReplay).length, 1); const stock = await prisma.inventoryRuntimeStock.findFirst({ where: f.scope }); assert.equal(stock.activeReservedQuantity, 0); assert.equal(stock.physicalQuantity, action === 'consume' ? 0 : 1); } });

pg('consume and release are idempotent and never double-decrement stock', async () => { const consumedFixture = await fixture(); const c = command(consumedFixture, `consume_${crypto.randomUUID()}`); const reserved = await consumedFixture.service.reserve(c.request, c.context); const ctx = { organizationId: consumedFixture.scope.organizationId, actorType: 'SYSTEM', actorId: 'test', idempotencyKey: `consume_op_${crypto.randomUUID()}` }; await consumedFixture.service.consume(reserved.reservation.reservationId, {}, ctx); const replay = await consumedFixture.service.consume(reserved.reservation.reservationId, {}, ctx); assert.equal(replay.idempotentReplay, true); assert.equal((await prisma.inventoryRuntimeStock.findFirst({ where: consumedFixture.scope })).physicalQuantity, 0);
  const releasedFixture = await fixture(); const r = command(releasedFixture, `release_${crypto.randomUUID()}`); const held = await releasedFixture.service.reserve(r.request, r.context); await releasedFixture.service.release(held.reservation.reservationId, {}, { organizationId: releasedFixture.scope.organizationId, actorType: 'SYSTEM', actorId: 'test', idempotencyKey: `release_op_${crypto.randomUUID()}` }); const again = await releasedFixture.service.release(held.reservation.reservationId, {}, { organizationId: releasedFixture.scope.organizationId }); assert.equal(again.idempotentReplay, true); assert.equal((await prisma.inventoryRuntimeStock.findFirst({ where: releasedFixture.scope })).activeReservedQuantity, 0); });

pg('expiration survives service restart and test consumption records TEST_CONSUMPTION', async () => { let now = new Date('2026-08-21T00:00:00Z'); const f = await fixture({ clock: () => now }); const c = command(f, `expire_${crypto.randomUUID()}`, { expiresAt: new Date(now.getTime() + 1000), operationType: 'OPERATOR_TEST' }); const held = await f.service.reserve(c.request, c.context); now = new Date(now.getTime() + 2000); const restarted = new PostgresInventoryReservationService({ prisma, clock: () => now }); await restarted.expireDue({ organizationId: f.scope.organizationId }); assert.equal((await restarted.list({}, { organizationId: f.scope.organizationId }))[0].status, 'EXPIRED');
  const tf = await fixture(); const tc = command(tf, `test_${crypto.randomUUID()}`, { operationType: 'MAINTENANCE_TEST' }); const tr = await tf.service.reserve(tc.request, tc.context); await tf.service.consume(tr.reservation.reservationId, {}, { organizationId: tf.scope.organizationId, actorType: 'OPERATOR', actorId: 'operator', idempotencyKey: `test_consume_${crypto.randomUUID()}` }); assert.equal((await prisma.inventoryRuntimeMovement.findFirst({ where: { sourceId: tr.reservation.reservationId } })).movementType, 'TEST_CONSUMPTION'); });

pg('tenant and machine isolation fail closed and outbox failure rolls reserve back', async () => { const f = await fixture(); const bad = command(f, `tenant_${crypto.randomUUID()}`); bad.context.organizationId = 'other'; await assert.rejects(() => f.service.reserve(bad.request, bad.context), { code: 'INVENTORY_TENANT_SCOPE_MISMATCH' }); const machine = command(f, `machine_${crypto.randomUUID()}`, { machineId: 'other-machine' }); await assert.rejects(() => f.service.reserve(machine.request, machine.context), { code: 'INVENTORY_MACHINE_LOCATION_MISMATCH' });
  const duplicateKey = `inventory:rollback_${crypto.randomUUID()}:INVENTORY_RESERVED`; await prisma.transactionalOutboxEvent.create({ data: { eventId: `event_${crypto.randomUUID()}`, eventType: 'TEST', aggregateType: 'TEST', aggregateId: 'test', organizationId: f.scope.organizationId, payload: {}, idempotencyKey: duplicateKey } }); const rollback = command(f, duplicateKey.split(':')[1]); await assert.rejects(() => f.service.reserve(rollback.request, rollback.context)); assert.equal((await prisma.inventoryRuntimeStock.findFirst({ where: f.scope })).activeReservedQuantity, 0); });

pg('PostgreSQL rejects impossible reservation item quantities', async () => {
  const f = await fixture({ quantity: 10 }); const c = command(f, `db_quantity_${crypto.randomUUID()}`); const held = await f.service.reserve(c.request, c.context); const item = held.reservation.items[0];
  for (const data of [{ quantity: 0 }, { quantity: -1 }, { reservedQuantity: -1 }, { consumedQuantity: -1 }, { releasedQuantity: -1 }, { consumedQuantity: 2 }, { releasedQuantity: 2 }, { consumedQuantity: 0.6, releasedQuantity: 0.6 }]) await assert.rejects(() => prisma.inventoryRuntimeReservationItem.update({ where: { id: item.id }, data }));
});

pg('one invalid item rolls back the complete multi-item quantity transaction', async () => {
  const f = await fixture({ quantity: 10, itemCount: 2 }); const c = command(f, `db_multi_${crypto.randomUUID()}`); const held = await f.service.reserve(c.request, c.context); const [first, second] = held.reservation.items;
  await assert.rejects(() => prisma.$transaction(async (tx) => { await tx.inventoryRuntimeReservationItem.update({ where: { id: first.id }, data: { consumedQuantity: 1 } }); await tx.inventoryRuntimeReservationItem.update({ where: { id: second.id }, data: { consumedQuantity: 2 } }); }));
  const rows = await prisma.inventoryRuntimeReservationItem.findMany({ where: { reservationId: held.reservation.reservationId } }); assert.ok(rows.every((row) => row.consumedQuantity === 0));
});
