const test = require('node:test');
const assert = require('node:assert/strict');
const { SaleFlowService, InMemorySaleFlowRepository, SimulatorPaymentAdapter, SimulatorMachineAdapter, presentSaleFlow } = require('../src/modules/sale_flow');
let sequence = 0;
function fixture(store, machine = 'DISPENSED') {
  const repository = new InMemorySaleFlowRepository(store); const orders = new Map(); const calls = { complete: 0, consume: 0, refund: 0, loyalty: 0 };
  const service = new SaleFlowService({ repository, paymentAdapter: new SimulatorPaymentAdapter(), machineAdapter: new SimulatorMachineAdapter({ outcome: machine }), organizationContext: { resolveByMachine: async () => ({ organizationId: 'org_1', locationId: 'location_1' }) }, inventory: { checkAndReserve: async () => ({ available: true, reservationId: 'reservation_1' }), calculatePrice: async () => ({ totalAmount: 190, currency: 'RUB' }), consume: async () => { calls.consume += 1; }, release: async () => {} }, orderDomain: { create: async (input) => { const value = { ...input, orderId: `order_${++sequence}` }; orders.set(value.orderId, value); return value; }, getPaymentDetails: async () => ({ amount: 190, currency: 'RUB' }), confirmPayment: async () => {}, rejectPayment: async () => {}, getFulfillmentDetails: async () => ({}), complete: async () => { calls.complete += 1; }, requireRefund: async () => { calls.refund += 1; } }, loyalty: { registerPurchase: async () => { calls.loyalty += 1; } } });
  return { repository, service, calls, store: repository.store };
}
const request = { customerId: 'customer_1', machineId: 'machine_1', product: { baseProductId: 'product_1', toppingId: 'topping_1', additionId: 'syrup_1' } };
async function create(f, key = `create_${++sequence}`) { return f.service.create(request, { idempotencyKey: key, correlationId: `corr_${key}` }); }

test('repository создаёт и читает процесс по основным ключам', async () => { const f = fixture(); const flow = await create(f); assert.equal((await f.repository.getById(flow.flowId)).orderId, flow.orderId); assert.equal((await f.repository.getByOrderId(flow.orderId)).flowId, flow.flowId); assert.equal((await f.repository.getByCorrelationId(flow.correlationId)).flowId, flow.flowId); });
test('оптимистическая блокировка допускает только одно конкурентное изменение', async () => { const f = fixture(); const flow = await create(f); const results = await Promise.allSettled([f.repository.compareAndSetState(flow.flowId, flow.version, 'PAID'), f.repository.compareAndSetState(flow.flowId, flow.version, 'PAID')]); assert.equal(results.filter((v) => v.status === 'fulfilled').length, 1); assert.equal(results.find((v) => v.status === 'rejected').reason.code, 'SALE_FLOW_VERSION_CONFLICT'); });
test('состояние PAID переживает пересоздание repository и service', async () => { const f = fixture(); const flow = await create(f); await f.service.pay(flow.orderId, {}, { idempotencyKey: 'payment_restart' }); const restarted = fixture(f.store); assert.equal((await restarted.repository.getByOrderId(flow.orderId)).currentState, 'PAID'); });
test('повторный payment callback после restart не выполняет переход', async () => { const f = fixture(); const flow = await create(f); await f.service.pay(flow.orderId, {}, { idempotencyKey: 'payment_duplicate' }); const restarted = fixture(f.store); const replay = await restarted.service.pay(flow.orderId, {}, { idempotencyKey: 'payment_duplicate' }); assert.equal(replay.duplicate, true); assert.equal((await restarted.repository.getByOrderId(flow.orderId)).version, 2); });
test('recovery помечает PAID безопасным, а DISPENSING требующим сверки', async () => { const f = fixture(); const paid = await create(f); await f.service.pay(paid.orderId, {}, { idempotencyKey: 'paid_recovery' }); const dispensing = await create(f); await f.service.pay(dispensing.orderId, {}, { idempotencyKey: 'dispensing_payment' }); const token = await f.service.authorize(dispensing.orderId); f.service.machineAdapter = new SimulatorMachineAdapter({ outcome: 'ACCEPTED' }); await f.service.dispense(token.tokenId); const restarted = fixture(f.store); await restarted.service.recover(); assert.equal((await restarted.repository.getByOrderId(paid.orderId)).recoveryStatus, 'SAFE_TO_RESUME'); assert.equal((await restarted.repository.getByOrderId(dispensing.orderId)).recoveryStatus, 'NEEDS_RECONCILIATION'); });
test('COMPLETED терминален и duplicate DISPENSED после restart не создаёт эффекты', async () => { const f = fixture(); const flow = await create(f); await f.service.pay(flow.orderId, {}, { idempotencyKey: 'complete_payment' }); const token = await f.service.authorize(flow.orderId); await f.service.dispense(token.tokenId); const restarted = fixture(f.store); await restarted.service.handleMachineResult(flow.orderId, { status: 'DISPENSED', commandId: `sim_dispense_${flow.orderId}` }, { idempotencyKey: `sim_dispense_${flow.orderId}` }); assert.equal((await restarted.repository.getByOrderId(flow.orderId)).currentState, 'COMPLETED'); assert.equal(restarted.calls.complete, 0); assert.equal(restarted.calls.consume, 0); });
test('REFUND_REQUIRED и его marker переживают restart', async () => { const f = fixture(null, 'FAILED'); const flow = await create(f); await f.service.pay(flow.orderId, {}, { idempotencyKey: 'refund_payment' }); const token = await f.service.authorize(flow.orderId); await f.service.dispense(token.tokenId); const restarted = fixture(f.store, 'FAILED'); assert.equal((await restarted.repository.getByOrderId(flow.orderId)).currentState, 'REFUND_REQUIRED'); await restarted.service.handleMachineResult(flow.orderId, { status: 'FAILED', commandId: `sim_dispense_${flow.orderId}` }, { idempotencyKey: `sim_dispense_${flow.orderId}` }); assert.equal(restarted.calls.refund, 0); });
test('idempotency различает незавершённую и завершённую операцию', async () => { const f = fixture(); const flow = await create(f); await f.repository.saveIdempotencyKey({ flowId: flow.flowId, key: 'pending_key', operationType: 'MACHINE_CALLBACK', source: 'TEST', requestHash: 'hash', status: 'STARTED' }); assert.equal((await f.repository.getIdempotencyKey('pending_key')).status, 'STARTED'); await f.repository.completeIdempotencyKey('pending_key', 'result_1'); assert.equal((await new InMemorySaleFlowRepository(f.store).getIdempotencyKey('pending_key')).status, 'COMPLETED'); await assert.rejects(() => f.repository.saveIdempotencyKey({ flowId: flow.flowId, key: 'pending_key', operationType: 'MACHINE_CALLBACK', source: 'TEST', requestHash: 'hash' }), { code: 'SALE_FLOW_DUPLICATE' }); });
test('Admin представление русское и не раскрывает секреты', async () => { const f = fixture(); const flow = await create(f); const view = presentSaleFlow({ ...flow, persistenceMode: 'POSTGRESQL' }); assert.equal(view.persistence, 'Состояние сохранено'); assert.equal(view.fields['Состояние процесса'], 'Ожидает оплату'); assert.equal(view.fields['Статус восстановления'], 'Можно безопасно продолжить'); });
test('health проверяет чтение, запись и транзакции repository', async () => { const f = fixture(); assert.deepEqual(await f.service.health(), { status: 'HEALTHY', repository: 'IN_MEMORY_TEST', readable: true, writable: true, transactional: true }); });
