const test=require('node:test');
const assert=require('node:assert/strict');
const {InMemoryOutboxRepository,OutboxWorker,RetryPolicy,InMemoryPublisher,validateEvent,OutboxAdminService}=require('../src/modules/transactional_outbox');

let n=0;const event=(extra={})=>({eventId:`event_${++n}`,eventType:'PAYMENT_CONFIRMED',eventVersion:1,aggregateType:'SALE_FLOW',aggregateId:'flow_1',organizationId:'org_a',machineId:'machine_1',saleFlowId:'flow_1',payload:{orderId:'order_1'},occurredAt:new Date('2026-08-20T00:00:00Z'),idempotencyKey:`key_${n}`,...extra});

test('eventId and idempotencyKey are unique, including concurrent creation',async()=>{const r=new InMemoryOutboxRepository();const same=event();const results=await Promise.allSettled([r.createEvent(same),r.createEvent({...same,eventId:'other'})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(await r.getPendingCount({organizationId:'org_a'}),1);await assert.rejects(r.createEvent({...event(),eventId:same.eventId}));});
test('secret fields are rejected recursively without exposing values',()=>{const sensitiveValue='must-never-appear-in-error';const cases=[{password:sensitiveValue},{customer:{token:sensitiveValue}},{customer:{integration:{apiKey:sensitiveValue}}},{items:[{authorization:sensitiveValue}]},{items:[{nested:{clientSecret:sensitiveValue}}]}];for(const payload of cases){let error;try{validateEvent(event({payload}));}catch(caught){error=caught;}assert.equal(error?.code,'OUTBOX_VALIDATION_FAILED');assert.equal(error.message.includes(sensitiveValue),false);}});
test('secret field matching is case-insensitive and supports snake_case',()=>{for(const key of ['APIKEY','ApiKey','authorization','Authorization','ACCESS_TOKEN','access_token','refresh_token','api_key','client_secret'])assert.throws(()=>validateEvent(event({payload:{[key]:'sensitive-value'}})),new RegExp(key,'i'));});
test('safe business field names are not rejected by substring matching',()=>{for(const key of ['productTokenCount','tokenizedLabel','secretaryName','authorizationStatus'])assert.doesNotThrow(()=>validateEvent(event({payload:{[key]:'safe-value'}})));});
test('two workers never claim the same event',async()=>{const r=new InMemoryOutboxRepository();await r.createEvent(event());const [a,b]=await Promise.all([r.claimPendingEvents({workerId:'a'}),r.claimPendingEvents({workerId:'b'})]);assert.equal(a.length+b.length,1);});
test('successful worker marks PUBLISHED and never republishes it',async()=>{const r=new InMemoryOutboxRepository();const p=new InMemoryPublisher();await r.createEvent(event());const w=new OutboxWorker({repository:r,publisher:p,workerId:'w'});await w.runOnce();await w.runOnce();assert.equal(p.published.length,1);assert.equal((await r.list({}, {organizationId:'org_a'}))[0].status,'PUBLISHED');});
test('retry uses deterministic backoff and reaches DEAD_LETTER',async()=>{let now=new Date('2026-08-20T00:00:00Z');const r=new InMemoryOutboxRepository();await r.createEvent(event({maxAttempts:2,availableAt:now}));const w=new OutboxWorker({repository:r,publisher:new InMemoryPublisher({fail:true}),workerId:'w',clock:()=>now,retryPolicy:new RetryPolicy({baseDelayMs:100,maxDelayMs:1000})});await w.runOnce();let row=(await r.list({}, {organizationId:'org_a'}))[0];assert.equal(row.status,'RETRY');assert.equal(row.availableAt.getTime(),now.getTime()+100);now=row.availableAt;await w.runOnce();assert.equal((await r.list({}, {organizationId:'org_a'}))[0].status,'DEAD_LETTER');});
test('expired PROCESSING lease is recovered',async()=>{const r=new InMemoryOutboxRepository();await r.createEvent(event({availableAt:new Date(0)}));await r.claimPendingEvents({workerId:'crashed',now:new Date(1000)});assert.equal((await r.releaseExpiredLocks({before:new Date(2000),now:new Date(3000)})).count,1);assert.equal((await r.list({}, {organizationId:'org_a'}))[0].status,'RETRY');});
test('publish success followed by markPublished failure is retried with the same eventId after lease expiry',async()=>{let now=new Date('2026-08-20T00:00:00Z');const r=new InMemoryOutboxRepository();const p=new InMemoryPublisher();const created=await r.createEvent(event({availableAt:now}));const markPublished=r.markPublished.bind(r);let failAck=true;r.markPublished=async(...args)=>{if(failAck)throw new Error('SIMULATED_PROCESS_CRASH_BEFORE_MARK_PUBLISHED');return markPublished(...args);};const w=new OutboxWorker({repository:r,publisher:p,workerId:'w',clock:()=>now,leaseMs:1000});await assert.rejects(w.runOnce(),/SIMULATED_PROCESS_CRASH/);let row=(await r.list({}, {organizationId:'org_a'}))[0];assert.equal(row.status,'PROCESSING');assert.equal(p.published.length,1);assert.equal(p.published[0].eventId,created.eventId);now=new Date(now.getTime()+1001);failAck=false;await w.runOnce();row=(await r.list({}, {organizationId:'org_a'}))[0];assert.equal(row.status,'PUBLISHED');assert.equal(p.published.length,2);assert.equal(p.published[1].eventId,created.eventId);assert.equal(row.eventId,created.eventId);});
test('tenant scope cannot read another organization',async()=>{const r=new InMemoryOutboxRepository();await r.createEvent(event());assert.equal((await r.list({}, {organizationId:'org_b'})).length,0);assert.equal((await r.list({}, {organizationId:'org_a'})).length,1);});
test('admin retry is explicit and audited',async()=>{const r=new InMemoryOutboxRepository();const e=await r.createEvent(event({status:'DEAD_LETTER'}));const audit=[];const s=new OutboxAdminService({repository:r,auditRepository:{record:async(x)=>audit.push(x)}});const result=await s.retry(e.eventId,{roles:['ADMIN'],organizationId:'org_a',actorId:'admin',correlationId:'corr'});assert.equal(result.status,'RETRY');assert.equal(audit[0].action,'RETRY_DEAD_LETTER');});
