const test = require('node:test'); const assert = require('node:assert/strict');
const { VideoSurveillanceRepository, VideoSurveillanceService, VideoCamera, MotionSensor, VideoRecordingPolicy, MockRtspCameraAdapter, InMemoryVideoRecorderAdapter, LocalMetadataVideoStorageAdapter } = require('../src/modules/video_surveillance');
function setup({ health, now = new Date('2026-07-24T10:00:00Z') } = {}) {
  const repository = new VideoSurveillanceRepository(), events = [], cameraAdapter = new MockRtspCameraAdapter({ result: health });
  const service = new VideoSurveillanceService({ repository, cameraAdapter, recorderAdapter: new InMemoryVideoRecorderAdapter(), storageAdapter: new LocalMetadataVideoStorageAdapter(), eventPublisher: { publish: async (e) => events.push(e) }, clock: () => now });
  const camera = repository.saveCamera(new VideoCamera({ id: 'cam', machineId: 'm1', rtspUrlSecretRef: 'secret://cam', recordingMode: 'HYBRID', retentionHours: 72 }));
  repository.savePolicy(new VideoRecordingPolicy({ cameraId: 'cam', preBufferSeconds: 10, postBufferSeconds: 20, maximumRecordingSeconds: 60, zones: [{ zoneId: 'area', name: 'Зона', polygon: [], triggerRecording: true }] }));
  const pir = repository.saveSensor(new MotionSensor({ id: 'pir', machineId: 'm1', cameraId: 'cam', sensorType: 'PIR', cooldownSeconds: 15 }));
  const analytics = repository.saveSensor(new MotionSensor({ id: 'analytics', machineId: 'm1', cameraId: 'cam', sensorType: 'CAMERA_ANALYTICS' }));
  return { repository, service, camera, pir, analytics, events, cameraAdapter, ctx: { roles: ['PLATFORM_OWNER'], permissions: ['video:legal_hold'], actorId: 'owner' } };
}
test('PIR пробуждает камеру, но не подтверждает движение и не создаёт инцидент', async () => { const s = setup(); const result = await s.service.motion('pir', {}, s.ctx); assert.equal(result.awakened, true); assert.equal(result.confirmed, false); assert.equal(s.cameraAdapter.wakeCalls.length, 1); assert.equal(s.repository.incidents.size, 0); });
test('аналитика подтверждает движение и запускает запись с pre/post buffer', async () => { const s = setup(); const result = await s.service.motion('analytics', { zoneId: 'area' }, s.ctx); assert.equal(result.confirmed, true); assert.equal(result.session.startedAt.toISOString(), '2026-07-24T09:59:50.000Z'); assert.equal(result.session.plannedEndAt.toISOString(), '2026-07-24T10:00:20.000Z'); });
test('повторное движение продлевает запись без короткого нового файла', async () => { const s = setup(); const one = await s.service.motion('analytics', { zoneId: 'area' }, s.ctx); const two = await s.service.motion('analytics', { zoneId: 'area' }, s.ctx); assert.equal(one.session.id, two.session.id); assert.equal(two.session.extensions, 1); });
test('событие автомата запускает запись', async () => { const s = setup(); await s.service.handlePlatformEvent({ eventType: 'PAYMENT_CONFIRMED_FOR_MACHINE', eventId: 'evt', aggregateId: 'm1', correlationId: 'c', payload: { machineId: 'm1' } }); assert.equal(s.repository.activeSession('cam').triggerType, 'PAYMENT_CONFIRMED'); });
test('архив хранится 72 часа, удаляется по сроку и сохраняется при legal hold', async () => { const s = setup(); const session = await s.service.startOrExtend(s.camera, 'MANUAL_REQUEST', null, s.ctx); const fragment = await s.service.complete(session.id, s.ctx); assert.equal((fragment.retentionUntil - fragment.endedAt) / 3600000, 72); s.service.clock = () => new Date('2026-07-28T10:00:00Z'); await s.service.legalHold(fragment.id, true, 'Разбирательство', s.ctx); assert.deepEqual(await s.service.purgeExpired(), []); await s.service.legalHold(fragment.id, false, null, s.ctx); assert.deepEqual(await s.service.purgeExpired(), [fragment.id]); assert.ok(s.repository.listAudit().some((a) => a.action === 'FRAGMENT_DELETED')); });
test('legal hold требует отдельного разрешения ADMIN', async () => { const s = setup(); const session = await s.service.startOrExtend(s.camera, 'MANUAL_REQUEST', null, s.ctx); const fragment = await s.service.complete(session.id, s.ctx); await assert.rejects(() => s.service.legalHold(fragment.id, true, 'x', { roles: ['ADMIN'], actorId: 'a' }), (e) => e.code === 'VIDEO_LEGAL_HOLD_DENIED'); });
test('health check различает RTSP, авторизацию, отсутствие кадров, замерший поток и накопитель', async () => { for (const [patch, expected] of [[{networkReachable:false},'OFFLINE'],[{authorizationSuccessful:false},'AUTH_FAILED'],[{framesReceived:false},'STREAM_FAILED'],[{imageFrozen:true},'STREAM_FAILED'],[{sufficientFreeSpace:false},'STORAGE_FAILED']]) { const base = { networkReachable:true,rtspPortReachable:true,authorizationSuccessful:true,framesReceived:true,imageFrozen:false,cameraTimeSynchronized:true,localStorageAvailable:true,sufficientFreeSpace:true }; const s = setup({ health: { ...base, ...patch } }); assert.equal((await s.service.check('m1','cam',s.ctx)).status, expected); } });
test('RTSP URL и secret reference не возвращаются через API-модель', () => { const s = setup(); const output = s.service.getCamera('m1','cam',s.ctx); assert.equal(output.rtspUrlSecretRef, undefined); assert.equal(output.secretConfigured, true); assert.equal(output.liveView.transport, 'MEDIA_PROXY'); });
test('просмотр архива аудируется, роль без доступа отклоняется', () => { const s = setup(); s.service.listFragments('m1', s.ctx); assert.equal(s.repository.listAudit()[0].action, 'ARCHIVE_VIEWED'); assert.throws(() => s.service.listFragments('m1', { roles: ['OPERATOR'] }), (e) => e.code === 'VIDEO_ACCESS_DENIED'); });
