const crypto = require('crypto');
const TERMINAL = new Set(['DISPENSED','FAILED','CANCELED']);
const TRANSITIONS = Object.freeze({ CREATED:['AUTHORIZED'], AUTHORIZED:['QUEUED','CANCELED'], QUEUED:['DISPATCHING','CANCELED'], DISPATCHING:['SENT','RECONCILIATION_REQUIRED'], SENT:['ACCEPTED','DISPENSING','DISPENSED','FAILED','TIMED_OUT','RECONCILIATION_REQUIRED'], ACCEPTED:['DISPENSING','DISPENSED','FAILED','TIMED_OUT','RECONCILIATION_REQUIRED'], DISPENSING:['DISPENSED','FAILED','TIMED_OUT','RECONCILIATION_REQUIRED'], TIMED_OUT:['RECONCILIATION_REQUIRED'], RECONCILIATION_REQUIRED:['DISPENSED','FAILED'], DISPENSED:[], FAILED:['RECONCILIATION_REQUIRED'], CANCELED:[] });
const EVENT = { AUTHORIZED:'MACHINE_DISPENSE_AUTHORIZED', QUEUED:'MACHINE_COMMAND_QUEUED', SENT:'MACHINE_COMMAND_SENT', ACCEPTED:'MACHINE_COMMAND_ACCEPTED', DISPENSING:'MACHINE_DISPENSE_STARTED', DISPENSED:'MACHINE_DISPENSED', FAILED:'MACHINE_DISPENSE_FAILED', TIMED_OUT:'MACHINE_DISPENSE_TIMED_OUT', RECONCILIATION_REQUIRED:'MACHINE_RECONCILIATION_REQUIRED' };
class MachineDispenseService {
  constructor({ repository, inventory, orderDomain, provider, clock = () => new Date(), failureInjector = async () => {} }) { Object.assign(this, { repository, inventory, orderDomain, provider, clock, failureInjector }); }
  async createAuthorized(request, context = {}) {
    required(request, ['organizationId','machineId','locationId','orderId','saleFlowId','inventoryReservationId','idempotencyKey','provider']);
    const existing = await this.repository.findByFlow(request.organizationId, request.orderId, request.saleFlowId); if (existing) return same(existing, request);
    try { return await this.repository.transaction(async (repo, tx) => {
      const flow = await tx.saleFlow.findFirst({ where: { organizationId: request.organizationId, orderId: request.orderId, flowId: request.saleFlowId, machineId: request.machineId, locationId: request.locationId } });
      if (!flow || !['PAID','FULFILLMENT_AUTHORIZED'].includes(flow.currentState)) throw problem('DISPENSE_SALE_FLOW_NOT_AUTHORIZED','Sale Flow не разрешает выдачу.');
      const payment = await tx.payment.findFirst({ where: { organizationId: request.organizationId, orderId: request.orderId, saleFlowId: request.saleFlowId, status: 'SUCCEEDED' } }); if (!payment) throw problem('DISPENSE_PAYMENT_NOT_SUCCEEDED','Authoritative Payment не подтверждён.');
      const reservation = await tx.inventoryRuntimeReservation.findFirst({ where: { organizationId: request.organizationId, reservationId: request.inventoryReservationId, machineId: request.machineId, locationId: request.locationId, orderId: request.orderId, saleFlowId: request.saleFlowId, status: 'RESERVED' } }); if (!reservation) throw problem('DISPENSE_RESERVATION_NOT_RESERVED','Inventory reservation не находится в RESERVED.');
      const assignment = await tx.organizationMachineAssignment.findFirst({ where: { organizationId: request.organizationId, machineId: request.machineId, locationId: request.locationId, unassignedAt: null } }); if (!assignment) throw problem('DISPENSE_MACHINE_SCOPE_MISMATCH','Аппарат не принадлежит указанной организации/точке.');
      const now=this.clock(), id=`dispense_attempt_${crypto.randomUUID()}`, commandId=`machine_command_${crypto.randomUUID()}`;
      const attempt=await repo.create({ dispenseAttemptId:id, organizationId:request.organizationId, machineId:request.machineId, locationId:request.locationId, orderId:request.orderId, saleFlowId:request.saleFlowId, inventoryReservationId:request.inventoryReservationId, operationType:request.operationType||'CUSTOMER_SALE', commandId, idempotencyKey:request.idempotencyKey, status:'AUTHORIZED', requestedAt:now, provider:request.provider, correlationId:context.correlationId||flow.correlationId, causationId:context.causationId||null });
      await tx.saleFlow.update({ where:{flowId:flow.flowId}, data:{currentState:'FULFILLMENT_AUTHORIZED', fulfillmentAuthorizationReference:id, recoveryStatus:'SAFE_TO_RESUME', version:{increment:1}} });
      await this.fact(repo,attempt,'AUTHORIZED',context); await this.fact(repo,attempt,'QUEUED',context,{command:true});
      const moved=await tx.machineDispenseAttempt.update({where:{id:attempt.id},data:{status:'QUEUED',version:{increment:1}}}); return {attempt:moved,duplicate:false};
    }); } catch (error) { if (error.code === 'P2002') { const duplicate = await this.repository.findByFlow(request.organizationId, request.orderId, request.saleFlowId); if (duplicate) return same(duplicate, request); } throw error; }
  }
  async createAuthorizedFromPaidFlow(tx, flow, payment, context = {}) {
    if (!tx || !flow || !payment) throw problem('MACHINE_DISPENSE_COMPOSITION_INVALID','Production composition требует общую PostgreSQL transaction.',500);
    const request={organizationId:flow.organizationId,machineId:flow.machineId,locationId:flow.locationId,orderId:flow.orderId,saleFlowId:flow.flowId,inventoryReservationId:flow.inventoryReservationReference,idempotencyKey:`customer-sale:${flow.flowId}`,provider:'HUAXIN',operationType:'CUSTOMER_SALE'};
    const repo=new (this.repository.constructor)(tx);
    const existing=await tx.machineDispenseAttempt.findUnique({where:{organizationId_orderId_saleFlowId:{organizationId:request.organizationId,orderId:request.orderId,saleFlowId:request.saleFlowId}}});
    if(existing)return same(existing,request);
    const reservation=await tx.inventoryRuntimeReservation.findFirst({where:{organizationId:request.organizationId,reservationId:request.inventoryReservationId,machineId:request.machineId,locationId:request.locationId,orderId:request.orderId,saleFlowId:request.saleFlowId,status:'RESERVED'}});
    if(!reservation)throw problem('DISPENSE_RESERVATION_NOT_RESERVED','Inventory reservation не находится в RESERVED.');
    const assignment=await tx.organizationMachineAssignment.findFirst({where:{organizationId:request.organizationId,machineId:request.machineId,locationId:request.locationId,unassignedAt:null}});
    if(!assignment)throw problem('DISPENSE_MACHINE_SCOPE_MISMATCH','Аппарат не принадлежит указанной организации/точке.');
    const now=this.clock(),id=`dispense_attempt_${crypto.randomUUID()}`,commandId=`machine_command_${crypto.randomUUID()}`;
    const attempt=await repo.create({dispenseAttemptId:id,organizationId:request.organizationId,machineId:request.machineId,locationId:request.locationId,orderId:request.orderId,saleFlowId:request.saleFlowId,inventoryReservationId:request.inventoryReservationId,operationType:'CUSTOMER_SALE',commandId,idempotencyKey:request.idempotencyKey,status:'AUTHORIZED',requestedAt:now,provider:request.provider,correlationId:context.correlationId||flow.correlationId,causationId:context.causationId||payment.id});
    await this.fact(repo,attempt,'AUTHORIZED',context);await this.fact(repo,attempt,'QUEUED',context,{command:true});
    const moved=await tx.machineDispenseAttempt.update({where:{id:attempt.id},data:{status:'QUEUED',version:{increment:1}}});
    await tx.saleFlow.update({where:{flowId:flow.flowId},data:{currentState:'FULFILLMENT_AUTHORIZED',fulfillmentAuthorizationReference:attempt.id,recoveryStatus:'SAFE_TO_RESUME',version:{increment:1}}});
    return{attempt:moved,duplicate:false};
  }
  async createTestAuthorized(request, context = {}) {
    required(request, ['organizationId','machineId','locationId','inventoryReservationId','idempotencyKey','provider','operationType','operationReason']);
    if(!['OPERATOR_TEST','MAINTENANCE_TEST'].includes(request.operationType))throw problem('MACHINE_TEST_OPERATION_INVALID','Разрешены только OPERATOR_TEST и MAINTENANCE_TEST.',400);
    const actor=await this.validateTestActor(request,context);
    const existing=await this.repository.findByIdempotency(request.organizationId,request.idempotencyKey);if(existing)return same(existing,request);
    try{return await this.repository.transaction(async(repo,tx)=>{
      const reservation=await tx.inventoryRuntimeReservation.findFirst({where:{organizationId:request.organizationId,reservationId:request.inventoryReservationId,machineId:request.machineId,locationId:request.locationId,status:'RESERVED',operationType:request.operationType}});if(!reservation)throw problem('DISPENSE_TEST_RESERVATION_NOT_RESERVED','Тестовый Inventory reservation не находится в RESERVED.');
      const assignment=await tx.organizationMachineAssignment.findFirst({where:{organizationId:request.organizationId,machineId:request.machineId,locationId:request.locationId,unassignedAt:null}});if(!assignment)throw problem('DISPENSE_MACHINE_SCOPE_MISMATCH','Аппарат не принадлежит указанной организации/точке.');
      const now=this.clock(),id=`dispense_attempt_${crypto.randomUUID()}`,commandId=`machine_command_${crypto.randomUUID()}`;
      const authoritativeContext={...context,actorType:'ORGANIZATION_MEMBER',actorId:actor.id};
      const attempt=await repo.create({dispenseAttemptId:id,organizationId:request.organizationId,machineId:request.machineId,locationId:request.locationId,orderId:null,saleFlowId:null,inventoryReservationId:request.inventoryReservationId,operationType:request.operationType,commandId,idempotencyKey:request.idempotencyKey,status:'AUTHORIZED',requestedAt:now,provider:request.provider,correlationId:context.correlationId||id,causationId:context.causationId||null,requestedByActorType:'ORGANIZATION_MEMBER',requestedByActorId:actor.id,operationReason:request.operationReason,serviceContextSafe:sanitize(request.serviceContext||{})});
      await this.fact(repo,attempt,'AUTHORIZED',authoritativeContext,{operationReason:request.operationReason,serviceContext:sanitize(request.serviceContext||{})});await this.fact(repo,attempt,'QUEUED',authoritativeContext,{command:true});
      const moved=await tx.machineDispenseAttempt.update({where:{id:attempt.id},data:{status:'QUEUED',version:{increment:1}}});return{attempt:moved,duplicate:false};
    });}catch(error){if(error.code==='P2002'){const duplicate=await this.repository.findByIdempotency(request.organizationId,request.idempotencyKey);if(duplicate)return same(duplicate,request);}throw error;}
  }
  async validateTestActor(request,context){
    const identity=context.securityContext;
    if(!identity?.subject_id)throw problem('MACHINE_TEST_AUTHENTICATION_REQUIRED','Требуется подтверждённая сервером identity.',401);
    if(identity.subject_type!=='organization_member')throw problem('MACHINE_TEST_ACTOR_TYPE_FORBIDDEN','Тип инициатора тестовой выдачи недопустим.',403);
    if(identity.organization_id&&identity.organization_id!==request.organizationId)throw problem('MACHINE_TEST_ACTOR_FORBIDDEN','Инициатор относится к другой организации.',403);
    const allowed=request.operationType==='OPERATOR_TEST'?['OPERATOR','MACHINE_RESPONSIBLE']:['SERVICE_SPECIALIST'];
    const member=await this.repository.findAuthorizedTestActor(request.organizationId,identity.subject_id,allowed);
    if(!member)throw problem('MACHINE_TEST_ACTOR_FORBIDDEN','Инициатор не имеет допустимой активной роли в организации.',403);
    return member;
  }
  async deliverCommand(event) { let attempt=await this.repository.get(event.organizationId,event.aggregateId); if(!attempt)throw problem('DISPENSE_ATTEMPT_NOT_FOUND','Попытка выдачи не найдена.',404); if(['SENT','ACCEPTED','DISPENSING','DISPENSED'].includes(attempt.status))return {attempt,duplicate:true}; if(attempt.status==='DISPATCHING')return this.requireReconciliation(attempt,'SEND_OUTCOME_UNKNOWN_AFTER_WORKER_RESTART',{outboxEventId:event.eventId}); if(attempt.status!=='QUEUED')throw problem('DISPENSE_COMMAND_NOT_QUEUED','Команда не находится в QUEUED.'); attempt=(await this.transition(attempt,'DISPATCHING')).attempt; try { const result=await this.provider.sendDispenseCommand({commandId:attempt.commandId,idempotencyKey:attempt.commandId,machineId:attempt.machineId,orderId:attempt.orderId}); return this.transition(attempt,'SENT',{sentAt:this.clock(),providerCommandId:result.providerCommandId||attempt.commandId},{idempotencyKey:`send:${attempt.commandId}`}); } catch(error) { await this.requireReconciliation(attempt,'LOCAL_SENT_PROVIDER_UNKNOWN',{failureCode:error.code||'MACHINE_PROVIDER_SEND_FAILED'}); throw error; } }
  async receiveCallback(input) { required(input,['provider','providerEventId','providerCommandId','machineId','status']); const payloadSafe=sanitize(input.payload||{}),payloadFingerprint=hash({provider:input.provider,providerEventId:input.providerEventId,providerCommandId:input.providerCommandId,machineId:input.machineId,status:input.status,failureCode:input.failureCode||null,payloadSafe}); let inbox=await this.repository.findInbox(input.provider,input.providerEventId); if(inbox){assertSameCallback(inbox,input,payloadFingerprint);if(inbox.status==='PROCESSED')return{inbox,duplicate:true};} const attempt=await this.repository.getByCommand(input.provider,input.providerCommandId); if(!attempt||attempt.machineId!==input.machineId)throw problem('MACHINE_CALLBACK_TARGET_UNKNOWN','Callback не сопоставлен с аппаратом/командой.',404); if(!inbox)try{inbox=await this.repository.inbox({organizationId:attempt.organizationId,dispenseAttemptId:attempt.id,provider:input.provider,providerEventId:input.providerEventId,machineId:input.machineId,providerCommandId:input.providerCommandId,payloadSafe,payloadFingerprint,callbackStatus:input.status,callbackFailureCode:input.failureCode||null,callbackFailureMessageSafe:safeText(input.failureMessageSafe),physicalConsumptionUnknown:input.physicalConsumptionUnknown,correlationId:attempt.correlationId});}catch(error){if(error.code!=='P2002')throw error;inbox=await this.repository.findInbox(input.provider,input.providerEventId);assertSameCallback(inbox,input,payloadFingerprint);} const workerId=`callback-request-${crypto.randomUUID()}`;const claimed=await this.repository.claimInbox(inbox.id,{workerId,now:this.clock()});if(!claimed)return{inbox:await this.repository.findInbox(input.provider,input.providerEventId),duplicate:true};return this.processClaimedCallback(claimed,attempt); }
  async recoverCallback(inbox,{workerId}={}){if(inbox.status!=='PROCESSING'||inbox.processingLockedBy!==workerId)throw problem('MACHINE_CALLBACK_CLAIM_LOST','Callback recovery claim утрачен.',409);const attempt=await this.repository.get(inbox.organizationId,inbox.dispenseAttemptId);if(!attempt||attempt.machineId!==inbox.machineId)throw problem('MACHINE_CALLBACK_TARGET_UNKNOWN','Callback не сопоставлен с аппаратом/командой.',404);return this.processClaimedCallback(inbox,attempt);}
  async processClaimedCallback(inbox,attempt){try{return await this.repository.transaction(async(repo)=>{const owned=await repo.lockClaimedInbox(inbox.id,inbox.processingLockedBy,inbox.processingLeaseVersion);if(!owned)throw problem('MACHINE_CALLBACK_CLAIM_LOST','Callback recovery claim утрачен.',409);const current=await repo.get(attempt.organizationId,attempt.id);const scoped=new MachineDispenseService({repository:repo,inventory:this.inventory,orderDomain:this.orderDomain,provider:this.provider,clock:this.clock,failureInjector:this.failureInjector});const result=await scoped.applyPhysicalResult(current,inbox.callbackStatus,{providerEventId:inbox.providerEventId,failureCode:inbox.callbackFailureCode,failureMessageSafe:inbox.callbackFailureMessageSafe,physicalConsumptionUnknown:inbox.physicalConsumptionUnknown});await this.failureInjector('CALLBACK_FINALIZATION');const finalized=await repo.updateClaimedInbox(inbox.id,inbox.processingLockedBy,inbox.processingLeaseVersion,{status:'PROCESSED',processedAt:this.clock(),failedAt:null,lastFailureCode:null,processingLockedAt:null,processingLockedBy:null});if(finalized.count!==1)throw problem('MACHINE_CALLBACK_CLAIM_LOST','Callback recovery claim утрачен.',409);return{inbox:owned,result,duplicate:false};});}catch(error){if(error.code!=='MACHINE_CALLBACK_CLAIM_LOST')await this.repository.failClaimedInbox(inbox.id,inbox.processingLockedBy,inbox.processingLeaseVersion,error.code||'MACHINE_CALLBACK_FAILED',this.clock());throw error;}}
  async applyPhysicalResult(attempt,status,details={}) { if(status==='ACCEPTED'){if(['ACCEPTED','DISPENSING','DISPENSED'].includes(attempt.status))return{attempt,duplicate:true};const now=this.clock();return this.transition(attempt,'ACCEPTED',{sentAt:attempt.sentAt||now,acceptedAt:now,providerEventId:details.providerEventId});} if(status==='DISPENSING'){if(['DISPENSING','DISPENSED'].includes(attempt.status))return{attempt,duplicate:true};const now=this.clock();return this.transition(attempt,'DISPENSING',{sentAt:attempt.sentAt||now,acceptedAt:attempt.acceptedAt||now,startedAt:now,providerEventId:details.providerEventId});} if(status==='DISPENSED')return this.completeDispensed(attempt,details); if(status==='FAILED')return this.fail(attempt,details); throw problem('MACHINE_CALLBACK_STATUS_UNSUPPORTED','Статус callback не поддерживается.'); }
  async completeDispensed(attempt,details) {
    if(attempt.status==='DISPENSED')return {attempt,duplicate:true};
    if(attempt.status==='FAILED')return this.requireReconciliation(attempt,'CONFLICTING_TERMINAL_CALLBACK',{providerStatus:'DISPENSED'});
    if(attempt.status==='TIMED_OUT')attempt=(await this.transition(attempt,'RECONCILIATION_REQUIRED',{},{})).attempt;
    assertTransition(attempt.status,'DISPENSED');
    try{return await this.repository.transaction(async(repo,tx)=>{
      const now=this.clock();
      const claimed=await tx.machineDispenseAttempt.updateMany({where:{id:attempt.id,version:attempt.version,status:attempt.status},data:{status:'DISPENSED',sentAt:attempt.sentAt||now,acceptedAt:attempt.acceptedAt||now,startedAt:attempt.startedAt||now,completedAt:now,providerEventId:details.providerEventId||attempt.providerEventId,version:{increment:1}}});
      if(claimed.count!==1){const current=await tx.machineDispenseAttempt.findUnique({where:{id:attempt.id}});if(current?.status==='DISPENSED')return{attempt:current,duplicate:true};throw problem('MACHINE_DISPENSE_CONFLICT','Конкурентная финализация требует повторного чтения.');}
      await this.failureInjector('MACHINE_PERSISTENCE');const updated=await tx.machineDispenseAttempt.findUnique({where:{id:attempt.id}});
      await this.inventory.consume(attempt.inventoryReservationId,{idempotencyKey:`machine-consume:${attempt.commandId}`},{organizationId:attempt.organizationId,actorType:'SYSTEM',actorId:'machine-runtime',correlationId:attempt.correlationId,transactionClient:tx});await this.failureInjector('INVENTORY_CONSUME');
      if(attempt.operationType==='CUSTOMER_SALE'){await this.orderDomain.complete(attempt.orderId,{commandId:attempt.commandId,transactionClient:tx});await this.failureInjector('ORDER_COMPLETION');await tx.saleFlow.updateMany({where:{flowId:attempt.saleFlowId,currentState:{not:'COMPLETED'}},data:{currentState:'COMPLETED',completionOperationId:`machine:${attempt.commandId}`,completedAt:now,recoveryStatus:'NONE',version:{increment:1}}});await this.failureInjector('SALE_FLOW_COMPLETION');}
      await this.fact(repo,updated,'DISPENSED',{});await this.failureInjector('TRANSACTIONAL_OUTBOX');return{attempt:updated,duplicate:false};
    });}catch(error){await this.requireReconciliation(await this.repository.get(attempt.organizationId,attempt.id),'LOCAL_DISPENSED_PROVIDER_UNKNOWN',{persistenceFailure:error.code||'INTERNAL_COMPLETION_FAILED'});throw error;}
  }
  async fail(attempt,details) { if(attempt.status==='DISPENSED')return this.requireReconciliation(attempt,'CONFLICTING_TERMINAL_CALLBACK',{providerStatus:'FAILED'}); if(attempt.status==='FAILED')return {attempt,duplicate:true}; if(attempt.status==='TIMED_OUT')attempt=(await this.transition(attempt,'RECONCILIATION_REQUIRED',{},{})).attempt; const unknown=details.physicalConsumptionUnknown!==false; if(unknown)return this.requireReconciliation(attempt,'LOCAL_DISPENSING_PROVIDER_FAILED',details); return this.repository.transaction(async(repo,tx)=>{ const moved=await this.moveTx(repo,tx,attempt,'FAILED',{failedAt:this.clock(),failureCode:details.failureCode||'PROVIDER_FAILED',failureMessageSafe:safeText(details.failureMessageSafe)}); await this.inventory.release(attempt.inventoryReservationId,{idempotencyKey:`machine-release:${attempt.commandId}`},{organizationId:attempt.organizationId,actorType:'SYSTEM',actorId:'machine-runtime',correlationId:attempt.correlationId,transactionClient:tx}); if(attempt.operationType==='CUSTOMER_SALE')await tx.saleFlow.update({where:{flowId:attempt.saleFlowId},data:{currentState:'REFUND_REQUIRED',refundRequirementReference:`machine:${attempt.commandId}`,recoveryStatus:'NEEDS_RECONCILIATION',version:{increment:1}}}); return {attempt:moved,duplicate:false};}); }
  timeout(attemptId,organizationId){return this.repository.get(organizationId,attemptId).then(a=>this.transition(a,'TIMED_OUT',{timedOutAt:this.clock()}));}
  async reconcileUnfinished(organizationId,{limit=100}={}){const attempts=await this.repository.unfinished(organizationId,limit);const results=[];for(const attempt of attempts){if(attempt.status==='QUEUED')results.push({attempt,action:'WAITING_DURABLE_COMMAND_DELIVERY'});else if(attempt.status==='DISPATCHING')results.push(await this.requireReconciliation(attempt,'SEND_OUTCOME_UNKNOWN_AFTER_RESTART',{recovery:true}));else results.push(await this.reconcileAttempt(attempt));}return results;}
  async reconcileAttempt(attempt){let providerState;try{providerState=await this.provider.reconcileCommand({commandId:attempt.commandId,providerCommandId:attempt.providerCommandId,machineId:attempt.machineId});}catch(error){return this.requireReconciliation(attempt,'PROVIDER_STATE_UNKNOWN',{failureCode:error.code||'PROVIDER_RECONCILIATION_FAILED'});}if(!providerState||!['DISPENSED','FAILED','NOT_DISPENSED'].includes(providerState.status))return this.requireReconciliation(attempt,'PROVIDER_STATE_AMBIGUOUS',{providerStatus:providerState?.status||'UNKNOWN'});if(providerState.status==='DISPENSED')return this.completeDispensed(attempt,{providerEventId:providerState.providerEventId});if(providerState.status==='FAILED'||providerState.status==='NOT_DISPENSED')return this.fail(attempt,{physicalConsumptionUnknown:false,failureCode:providerState.failureCode||providerState.status});return this.requireReconciliation(attempt,'PROVIDER_STATE_AMBIGUOUS',{providerStatus:providerState.status});}
  async requireReconciliation(attempt,category,details={}) { if(attempt.status!=='RECONCILIATION_REQUIRED'&&!TERMINAL.has(attempt.status)) attempt=(await this.transition(attempt,'RECONCILIATION_REQUIRED',{},{})).attempt; const fingerprint=hash({attemptId:attempt.id,category,localStatus:attempt.status,details:sanitize(details)}); if(!await this.repository.findReconciliation(attempt.organizationId,fingerprint))await this.repository.reconcile({organizationId:attempt.organizationId,dispenseAttemptId:attempt.id,category,fingerprint,status:'MANUAL_REVIEW',localStatus:attempt.status,providerStatus:details.providerStatus||null,detailsSafe:sanitize(details)}); return {attempt,reconciliationRequired:true}; }
  async transition(attempt,to,data={},context={}){assertTransition(attempt.status,to);return this.repository.transaction(async(repo,tx)=>({attempt:await this.moveTx(repo,tx,attempt,to,data,context),duplicate:false}));}
  async moveTx(repo,tx,attempt,to,data={},context={}){const result=await repo.update(attempt.id,attempt.version,{status:to,...data});if(result.count!==1)throw problem('MACHINE_DISPENSE_CONFLICT','Конкурентный переход уже выполнен.');const updated=await tx.machineDispenseAttempt.findUnique({where:{id:attempt.id}});await this.fact(repo,updated,to,context);return updated;}
  async fact(repo,attempt,state,context={},extra={}){const eventType=EVENT[state];await repo.audit({organizationId:attempt.organizationId,dispenseAttemptId:attempt.id,action:state,actorType:context.actorType||'SYSTEM',actorId:context.actorId||null,correlationId:attempt.correlationId,detailsSafe:sanitize(extra)});if(eventType)await repo.outbox({eventId:`event_${crypto.randomUUID()}`,eventType,eventVersion:1,aggregateType:'MACHINE_DISPENSE',aggregateId:attempt.id,organizationId:attempt.organizationId,machineId:attempt.machineId,saleFlowId:attempt.saleFlowId,payload:{dispenseAttemptId:attempt.dispenseAttemptId,commandId:attempt.commandId,status:state,...extra},status:'PENDING',occurredAt:this.clock(),correlationId:attempt.correlationId,causationId:attempt.causationId,idempotencyKey:`machine:${attempt.commandId}:${eventType}`});}
}
function assertTransition(from,to){if(!TRANSITIONS[from]?.includes(to))throw problem('MACHINE_DISPENSE_TRANSITION_INVALID',`Переход ${from} -> ${to} запрещён.`);}
function required(v,keys){for(const k of keys)if(v[k]===undefined||v[k]===null||v[k]==='')throw problem('MACHINE_DISPENSE_VALIDATION_FAILED',`${k} обязателен.`,400);}
function same(a,r){const operationType=r.operationType||'CUSTOMER_SALE';const testMismatch=operationType!=='CUSTOMER_SALE'&&(a.operationReason!==r.operationReason||hash(a.serviceContextSafe||{})!==hash(sanitize(r.serviceContext||{})));if(a.machineId!==r.machineId||a.locationId!==r.locationId||a.inventoryReservationId!==r.inventoryReservationId||a.provider!==r.provider||a.operationType!==operationType||a.idempotencyKey!==r.idempotencyKey||testMismatch||(operationType==='CUSTOMER_SALE'&&(a.orderId!==r.orderId||a.saleFlowId!==r.saleFlowId)))throw problem('MACHINE_DISPENSE_IDEMPOTENCY_CONFLICT','Повторная команда отличается от исходной.');return{attempt:a,duplicate:true};}
function sanitize(value){if(!value||typeof value!=='object')return value||null;const out={};for(const[k,v]of Object.entries(value))if(!/(authorization|cookie|secret|token|credential|api.?key|password)/i.test(k))out[k]=typeof v==='object'?sanitize(v):v;return out;}
function safeText(v){return v?String(v).slice(0,500):null;} function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function assertSameCallback(prior,input,fingerprint){if(prior.providerCommandId!==input.providerCommandId||prior.machineId!==input.machineId||prior.callbackStatus!==input.status||prior.payloadFingerprint!==fingerprint)throw problem('MACHINE_CALLBACK_IDEMPOTENCY_CONFLICT','Повторный providerEventId содержит другие факты.');}
function problem(code,message,statusCode=409){return Object.assign(new Error(message),{code,statusCode});}
module.exports={MachineDispenseService,TRANSITIONS,TERMINAL};
