const { EventTypeDefinition } = require('./EventCenterModels');

const groups = {
  MACHINE: ['MACHINE_REGISTERED', 'MACHINE_CONNECTED', 'MACHINE_DISCONNECTED', 'MACHINE_CONNECTIVITY_DATA_STALE', 'MACHINE_RUNTIME_ERROR_ENTERED', 'MACHINE_RUNTIME_ERROR_RESOLVED', 'MACHINE_CYCLE_STARTED', 'MACHINE_CYCLE_COMPLETED', 'MACHINE_DOOR_OPENED', 'MACHINE_DOOR_CLOSED', 'MACHINE_IMPACT_DETECTED', 'MACHINE_TILT_DETECTED'],
  PAYMENT: ['PAYMENT_STARTED', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'PAYMENT_REFUNDED'],
  BUSINESS: ['PURCHASE_STARTED', 'ORDER_CREATED', 'DISPENSE_STARTED', 'DISPENSE_COMPLETED', 'DISPENSE_FAILED', 'PRODUCT_NOT_ISSUED'],
  CUSTOMER: ['CUSTOMER_REGISTERED', 'CUSTOMER_PROFILE_UPDATED', 'CUSTOMER_JOINED_CLUB', 'CUSTOMER_BALANCE_REPLENISHED', 'CUSTOMER_BONUS_ACCRUED', 'CUSTOMER_BONUS_SPENT', 'CUSTOMER_REFERRAL_ACTIVATED'],
  INVENTORY: ['INVENTORY_RECEIVED', 'INVENTORY_RESERVED', 'INVENTORY_CONSUMED', 'INVENTORY_ADJUSTED', 'INVENTORY_LOW', 'INVENTORY_OUT_OF_STOCK'],
  MAINTENANCE: ['MAINTENANCE_REQUEST_CREATED', 'MAINTENANCE_ASSIGNED', 'MAINTENANCE_STARTED', 'MAINTENANCE_COMPLETED', 'MAINTENANCE_CANCELLED', 'COMPONENT_REPLACED', 'TEST_DISPENSE_STARTED', 'TEST_DISPENSE_COMPLETED'],
  CONNECTIVITY: ['SIM_REGISTERED', 'SIM_CHANGED', 'MOBILE_OPERATOR_CHANGED', 'CONNECTIVITY_DEGRADED', 'CONNECTIVITY_RESTORED', 'PING_CHECK_COMPLETED', 'SIGNAL_LEVEL_LOW'],
  VIDEO_SURVEILLANCE: ['CAMERA_REGISTERED', 'CAMERA_ONLINE', 'CAMERA_OFFLINE', 'CAMERA_STREAM_FAILED', 'MOTION_DETECTED', 'MOTION_CONFIRMED', 'VIDEO_RECORDING_STARTED', 'VIDEO_RECORDING_EXTENDED', 'VIDEO_RECORDING_COMPLETED', 'VIDEO_FRAGMENT_UPLOADED', 'VIDEO_FRAGMENT_DELETED', 'VIDEO_INCIDENT_CREATED', 'VIDEO_RETENTION_EXTENDED', 'VIDEO_LEGAL_HOLD_APPLIED', 'VIDEO_LEGAL_HOLD_RELEASED'],
  SECURITY: ['UNAUTHORIZED_ACCESS_ATTEMPT', 'SUSPICIOUS_ACTIVITY_DETECTED', 'ACCESS_PERMISSION_CHANGED'],
};
const subjectByCategory = { MACHINE: 'MACHINE', PAYMENT: 'PAYMENT', BUSINESS: 'ORDER', CUSTOMER: 'CUSTOMER', INVENTORY: 'INVENTORY_OPERATION', MAINTENANCE: 'MAINTENANCE_REQUEST', CONNECTIVITY: 'MACHINE', VIDEO_SURVEILLANCE: 'CAMERA', SECURITY: 'SYSTEM' };
const severity = { MACHINE_DISCONNECTED: 'WARNING', MACHINE_RUNTIME_ERROR_ENTERED: 'INCIDENT', PAYMENT_FAILED: 'WARNING', DISPENSE_FAILED: 'INCIDENT', PRODUCT_NOT_ISSUED: 'INCIDENT', INVENTORY_LOW: 'WARNING', INVENTORY_OUT_OF_STOCK: 'INCIDENT', CONNECTIVITY_DEGRADED: 'WARNING', CAMERA_OFFLINE: 'WARNING', CAMERA_STREAM_FAILED: 'INCIDENT', UNAUTHORIZED_ACCESS_ATTEMPT: 'INCIDENT', SUSPICIOUS_ACTIVITY_DETECTED: 'CRITICAL' };
const titles = { MACHINE_DISCONNECTED: 'Автомат отключён', PAYMENT_CONFIRMED: 'Платёж подтверждён', VIDEO_RECORDING_STARTED: 'Видеозапись начата' };

function createEventTypeRegistry() {
  const definitions = new Map();
  for (const [category, codes] of Object.entries(groups)) for (const eventCode of codes) {
    const definition = new EventTypeDefinition({
      eventCode, version: 1, titleTemplate: titles[eventCode] || eventCode.replaceAll('_', ' ').toLowerCase(),
      summaryTemplate: 'Событие зарегистрировано в Центре событий.', category,
      defaultSeverity: severity[eventCode] || (category === 'BUSINESS' || category === 'PAYMENT' || category === 'CUSTOMER' ? 'BUSINESS' : 'INFO'),
      subjectType: subjectByCategory[category], acknowledgementRequired: ['INCIDENT', 'CRITICAL', 'EMERGENCY'].includes(severity[eventCode]),
      sourceDomain: category.toLowerCase(), metadata: { foundationVersion: 1 },
    });
    definitions.set(definition.id, definition);
  }
  return {
    get(eventCode, version = 1) { return definitions.get(`${eventCode}.v${version}`) || null; },
    list() { return [...definitions.values()]; },
    register(value) { const definition = new EventTypeDefinition(value); definitions.set(definition.id, definition); return definition; },
  };
}
module.exports = { createEventTypeRegistry };
