'use strict';

function normalizeTimeForPrisma(value) {
  if (value instanceof Date) return value;
  if (typeof value !== 'string' || !/^\d{2}:\d{2}(:\d{2})?$/.test(value)) return value;
  const normalized = value.length === 5 ? `${value}:00` : value;
  return new Date(`1970-01-01T${normalized}.000Z`);
}
function normalizeSchedules(schedules = []) { return schedules.map((item) => ({ ...item, startTime: normalizeTimeForPrisma(item.startTime), endTime: normalizeTimeForPrisma(item.endTime) })); }
function timeFromPrisma(value) { return value instanceof Date ? value.toISOString().slice(11, 19) : value; }
function serializeCampaign(campaign) { if (!campaign || !campaign.currentVersion) return campaign; return { ...campaign, currentVersion: { ...campaign.currentVersion, schedules: (campaign.currentVersion.schedules || []).map((item) => ({ ...item, startTime: timeFromPrisma(item.startTime), endTime: timeFromPrisma(item.endTime) })) } }; }
function versionScalarData(version, createdBy) { return { benefitType: version.benefitType, benefitValue: version.benefitValue, priority: version.priority || 0, stackingMode: version.stackingMode || 'BEST_PRICE', exclusiveGroup: version.exclusiveGroup || null, priceLockSeconds: version.priceLockSeconds || 300, startsAt: version.startsAt || null, endsAt: version.endsAt || null, timezone: version.timezone || 'Europe/Moscow', approvalPolicy: version.approvalPolicy || 'SINGLE_APPROVAL', isManualOverride: Boolean(version.isManualOverride), budgetAmount: version.budgetAmount ?? null, budgetAction: version.budgetAction || 'STOP', maxApplications: version.maxApplications ?? null, maxApplicationsPerCustomer: version.maxApplicationsPerCustomer ?? null, minimumFinalPrice: version.minimumFinalPrice ?? null, metadata: version.metadata || undefined, createdBy }; }

class PromotionRepository {
  constructor(prisma) { if (!prisma) throw new Error('Prisma client is required.'); this.prisma = prisma; }
  async createDraft(input) { const { code, name, description = null, createdBy, version } = input; return this.prisma.$transaction(async (tx) => { const campaign = await tx.promotionCampaign.create({ data: { code, name, description, status: 'DRAFT', createdBy } }); const createdVersion = await tx.promotionVersion.create({ data: { campaignId: campaign.id, version: version.version || 1, ...versionScalarData(version, createdBy), schedules: { create: normalizeSchedules(version.schedules || []) }, targets: { create: version.targets || [] }, audiences: { create: version.audiences || [] }, rules: { create: version.rules || [] }, channels: { create: version.channels || [] } } }); await tx.promotionCampaign.update({ where: { id: campaign.id }, data: { currentVersionId: createdVersion.id } }); await tx.promotionEvent.create({ data: { campaignId: campaign.id, promotionVersionId: createdVersion.id, eventType: 'DRAFT_CREATED', actorType: 'ADMIN_USER', actorId: createdBy, newValue: { code, name, version: createdVersion.version } } }); return this.getCampaignById(campaign.id, tx); }); }
  async getCampaignById(id, client = this.prisma) { const campaign = await client.promotionCampaign.findUnique({ where: { id }, include: { currentVersion: { include: { schedules: true, targets: true, audiences: true, rules: true, channels: true } } } }); return serializeCampaign(campaign); }
  async updateDraft({ campaignId, patch, actorId }) { return this.prisma.$transaction(async (tx) => { const current = await this.getCampaignById(campaignId, tx); if (!current) return null; const campaignData = {}; if (Object.prototype.hasOwnProperty.call(patch, 'name')) campaignData.name = patch.name; if (Object.prototype.hasOwnProperty.call(patch, 'description')) campaignData.description = patch.description; if (Object.keys(campaignData).length) await tx.promotionCampaign.update({ where: { id: campaignId }, data: campaignData }); if (patch.version) { const versionId = current.currentVersion.id; const versionPatch = { ...patch.version }; ['schedules','targets','audiences','rules','channels'].forEach((key) => delete versionPatch[key]); if (Object.keys(versionPatch).length) await tx.promotionVersion.update({ where: { id: versionId }, data: versionPatch }); for (const [key, model] of [['schedules','promotionSchedule'],['targets','promotionTarget'],['audiences','promotionAudience'],['rules','promotionRule'],['channels','promotionChannel']]) { if (patch.version[key]) { await tx[model].deleteMany({ where: { promotionVersionId: versionId } }); const rows = key === 'schedules' ? normalizeSchedules(patch.version[key]) : patch.version[key]; if (rows.length) await tx[model].createMany({ data: rows.map((x) => ({ ...x, promotionVersionId: versionId })) }); } } } await tx.promotionCampaign.update({ where: { id: campaignId }, data: { status: 'DRAFT' } }); await tx.promotionEvent.create({ data: { campaignId, promotionVersionId: current.currentVersionId, eventType: 'DRAFT_UPDATED', actorType: 'ADMIN_USER', actorId, oldValue: { status: current.status }, newValue: patch } }); return this.getCampaignById(campaignId, tx); }); }
  async createVersion({ campaignId, version, actorId }) { return this.prisma.$transaction(async (tx) => { const campaign = await this.getCampaignById(campaignId, tx); if (!campaign) return null; const max = await tx.promotionVersion.aggregate({ where: { campaignId }, _max: { version: true } }); const nextVersion = (max._max.version || 0) + 1; const created = await tx.promotionVersion.create({ data: { campaignId, version: nextVersion, ...versionScalarData(version, actorId), schedules: { create: normalizeSchedules(version.schedules || []) }, targets: { create: version.targets || [] }, audiences: { create: version.audiences || [] }, rules: { create: version.rules || [] }, channels: { create: version.channels || [] } } }); await tx.promotionCampaign.update({ where: { id: campaignId }, data: { currentVersionId: created.id, status: 'DRAFT' } }); await tx.promotionEvent.create({ data: { campaignId, promotionVersionId: created.id, eventType: 'VERSION_CREATED', actorType: 'ADMIN_USER', actorId, oldValue: { currentVersionId: campaign.currentVersionId }, newValue: { currentVersionId: created.id, version: nextVersion } } }); return this.getCampaignById(campaignId, tx); }); }
  async updateCampaignStatus({ campaignId, status, actorId, validationResult }) { return this.transitionStatus({ campaignId, status, actorId, eventType: status === 'READY' ? 'VALIDATION_PASSED' : 'VALIDATION_FAILED', actorType: 'SYSTEM', metadata: validationResult }); }
  async transitionStatus({ campaignId, status, actorId, eventType, actorType = 'ADMIN_USER', reason = null, metadata = undefined, versionPatch = undefined }) { return this.prisma.$transaction(async (tx) => { const current = await tx.promotionCampaign.findUnique({ where: { id: campaignId } }); if (!current) return null; if (versionPatch && current.currentVersionId) await tx.promotionVersion.update({ where: { id: current.currentVersionId }, data: versionPatch }); const updated = await tx.promotionCampaign.update({ where: { id: campaignId }, data: { status, ...(status === 'ARCHIVED' ? { archivedAt: new Date() } : {}) } }); await tx.promotionEvent.create({ data: { campaignId, promotionVersionId: current.currentVersionId, eventType, actorType, actorId, oldValue: { status: current.status }, newValue: { status }, reason, metadata } }); return updated; }); }
  async countApprovals(promotionVersionId) { return this.prisma.promotionApproval.count({ where: { promotionVersionId, status: 'APPROVED' } }); }
}
module.exports = { PromotionRepository, normalizeSchedules, serializeCampaign };