function resource(type, value, attributes) { return { type, id: value.id, attributes }; }
function toOperatorDto(value) { return resource('operator', value, { display_name: value.displayName, role: String(value.role).toLowerCase(), status: String(value.status).toLowerCase() }); }
function toChecklistDto(value) { return resource('maintenance_checklist', value, { code: value.code, name: value.name, version: value.version, items: value.items, active: value.active }); }
function toTaskDto(value) { return resource('maintenance_task', value, { machine_id: value.machineId, checklist_id: value.checklistId, assigned_to_id: value.assignedToId, status: String(value.status).toLowerCase(), checklist_results: value.checklistResults || null, completed_at: value.completedAt ? value.completedAt.toISOString() : null }); }
function toTestRunDto(result) { return resource('test_run', result.testRun, { machine_id: result.testRun.machineId, operator_id: result.testRun.operatorId, status: String(result.testRun.status).toLowerCase(), performed_at: result.testRun.performedAt.toISOString(), inventory_movements: result.inventoryMovements.map(toInventoryMovementDto) }); }
function toInventoryMovementDto(value) { return resource('inventory_movement', value, { machine_id: value.machineId, test_run_id: value.testRunId || null, movement_type: String(value.movementType).toLowerCase(), item_type: String(value.itemType).toLowerCase(), item_reference: value.itemReference || null, quantity: Number(value.quantity), unit: value.unit, reason: value.reason }); }
function toServiceLogDto(value) { return resource('service_log', value, { machine_id: value.machineId, maintenance_task_id: value.maintenanceTaskId || null, operator_id: value.operatorId, status: String(value.status).toLowerCase(), summary: value.summary, work_performed: value.workPerformed, approved_by_id: value.approvedById || null }); }
function toPhotoEvidenceDto(value) { return resource('photo_evidence', value, { storage_key: value.storageKey, content_type: value.contentType, checksum_sha256: value.checksumSha256, captured_at: value.capturedAt.toISOString() }); }
module.exports = { toChecklistDto, toInventoryMovementDto, toOperatorDto, toPhotoEvidenceDto, toServiceLogDto, toTaskDto, toTestRunDto };
