const MachineRuntimeState = Object.freeze(Object.fromEntries([
  'UNKNOWN','OFFLINE','BOOTING','IDLE','READY','CUSTOMER_SESSION','ORDER_PENDING',
  'PAYMENT_PENDING','PAYMENT_CONFIRMED','DISPENSE_AUTHORIZED','CUP_DISPENSING',
  'PRODUCT_DISPENSING','TOPPING_DISPENSING','COMPLETING','COMPLETED','TEST_MODE',
  'CLEANING','MAINTENANCE','OUT_OF_SERVICE','ERROR','RECOVERING','SHUTTING_DOWN',
].map((state) => [state, state])));
const StateCategory = Object.freeze({
  STABLE: Object.freeze(['UNKNOWN','OFFLINE','IDLE','READY','TEST_MODE','CLEANING','MAINTENANCE','OUT_OF_SERVICE','ERROR']),
  TRANSIENT: Object.freeze(['BOOTING','CUSTOMER_SESSION','ORDER_PENDING','PAYMENT_PENDING','PAYMENT_CONFIRMED','DISPENSE_AUTHORIZED','CUP_DISPENSING','PRODUCT_DISPENSING','TOPPING_DISPENSING','COMPLETING','RECOVERING','SHUTTING_DOWN']),
  TERMINAL: Object.freeze(['COMPLETED']),
});
module.exports = { MachineRuntimeState, StateCategory };
