CREATE TYPE "OperatorRole" AS ENUM ('OPERATOR', 'ADMIN');
CREATE TYPE "OperatorStatus" AS ENUM ('ACTIVE', 'SUSPENDED');
CREATE TYPE "MaintenanceTaskStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ServiceLogStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED');
CREATE TYPE "TestRunStatus" AS ENUM ('PASSED', 'FAILED');
CREATE TYPE "InventoryMovementType" AS ENUM ('CONSUMPTION', 'REPLENISHMENT', 'ADJUSTMENT');
CREATE TYPE "InventoryItemType" AS ENUM ('CUP', 'ICE_CREAM_MIX', 'TOPPING');

CREATE TABLE "Operator" ("id" TEXT NOT NULL, "displayName" TEXT NOT NULL, "externalSubject" TEXT, "role" "OperatorRole" NOT NULL DEFAULT 'OPERATOR', "status" "OperatorStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Operator_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OperatorPermission" ("id" TEXT NOT NULL, "operatorId" TEXT NOT NULL, "permission" TEXT NOT NULL, "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "grantedBy" TEXT, CONSTRAINT "OperatorPermission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MaintenanceChecklist" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "version" INTEGER NOT NULL, "items" JSONB NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "configuredById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MaintenanceChecklist_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MaintenanceTask" ("id" TEXT NOT NULL, "machineId" TEXT NOT NULL, "checklistId" TEXT NOT NULL, "assignedToId" TEXT NOT NULL, "completedById" TEXT, "status" "MaintenanceTaskStatus" NOT NULL DEFAULT 'OPEN', "checklistResults" JSONB, "notes" TEXT, "dueAt" TIMESTAMP(3), "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MaintenanceTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceLog" ("id" TEXT NOT NULL, "machineId" TEXT NOT NULL, "maintenanceTaskId" TEXT, "operatorId" TEXT NOT NULL, "status" "ServiceLogStatus" NOT NULL DEFAULT 'DRAFT', "summary" TEXT NOT NULL, "workPerformed" JSONB NOT NULL, "submittedAt" TIMESTAMP(3), "approvedById" TEXT, "approvedAt" TIMESTAMP(3), "approvalNote" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ServiceLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TestRun" ("id" TEXT NOT NULL, "machineId" TEXT NOT NULL, "operatorId" TEXT NOT NULL, "status" "TestRunStatus" NOT NULL, "notes" TEXT, "results" JSONB, "performedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TestRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryMovement" ("id" TEXT NOT NULL, "machineId" TEXT NOT NULL, "operatorId" TEXT NOT NULL, "testRunId" TEXT, "movementType" "InventoryMovementType" NOT NULL, "itemType" "InventoryItemType" NOT NULL, "itemReference" TEXT, "quantity" DOUBLE PRECISION NOT NULL, "unit" TEXT NOT NULL, "reason" TEXT NOT NULL, "idempotencyKey" TEXT, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InventoryMovement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PhotoEvidence" ("id" TEXT NOT NULL, "operatorId" TEXT NOT NULL, "maintenanceTaskId" TEXT, "serviceLogId" TEXT, "testRunId" TEXT, "storageKey" TEXT NOT NULL, "contentType" TEXT NOT NULL, "checksumSha256" TEXT NOT NULL, "capturedAt" TIMESTAMP(3) NOT NULL, "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB, CONSTRAINT "PhotoEvidence_pkey" PRIMARY KEY ("id"));
ALTER TABLE "PhotoEvidence" ADD CONSTRAINT "PhotoEvidence_exactly_one_reference_check" CHECK ((CASE WHEN "maintenanceTaskId" IS NULL THEN 0 ELSE 1 END) + (CASE WHEN "serviceLogId" IS NULL THEN 0 ELSE 1 END) + (CASE WHEN "testRunId" IS NULL THEN 0 ELSE 1 END) = 1);
CREATE TABLE "MachineSetting" ("id" TEXT NOT NULL, "machineId" TEXT NOT NULL, "key" TEXT NOT NULL, "value" JSONB NOT NULL, "updatedById" TEXT NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MachineSetting_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Operator_externalSubject_key" ON "Operator"("externalSubject");
CREATE UNIQUE INDEX "OperatorPermission_operatorId_permission_key" ON "OperatorPermission"("operatorId", "permission"); CREATE INDEX "OperatorPermission_permission_idx" ON "OperatorPermission"("permission");
CREATE UNIQUE INDEX "MaintenanceChecklist_code_version_key" ON "MaintenanceChecklist"("code", "version"); CREATE INDEX "MaintenanceChecklist_code_active_idx" ON "MaintenanceChecklist"("code", "active");
CREATE INDEX "MaintenanceTask_assignedToId_status_dueAt_idx" ON "MaintenanceTask"("assignedToId", "status", "dueAt"); CREATE INDEX "MaintenanceTask_machineId_status_idx" ON "MaintenanceTask"("machineId", "status");
CREATE INDEX "ServiceLog_machineId_createdAt_idx" ON "ServiceLog"("machineId", "createdAt"); CREATE INDEX "ServiceLog_status_submittedAt_idx" ON "ServiceLog"("status", "submittedAt");
CREATE INDEX "TestRun_machineId_performedAt_idx" ON "TestRun"("machineId", "performedAt"); CREATE INDEX "TestRun_operatorId_performedAt_idx" ON "TestRun"("operatorId", "performedAt");
CREATE UNIQUE INDEX "InventoryMovement_machineId_idempotencyKey_key" ON "InventoryMovement"("machineId", "idempotencyKey"); CREATE INDEX "InventoryMovement_machineId_occurredAt_idx" ON "InventoryMovement"("machineId", "occurredAt"); CREATE INDEX "InventoryMovement_testRunId_idx" ON "InventoryMovement"("testRunId");
CREATE UNIQUE INDEX "PhotoEvidence_storageKey_key" ON "PhotoEvidence"("storageKey"); CREATE INDEX "PhotoEvidence_maintenanceTaskId_idx" ON "PhotoEvidence"("maintenanceTaskId"); CREATE INDEX "PhotoEvidence_serviceLogId_idx" ON "PhotoEvidence"("serviceLogId"); CREATE INDEX "PhotoEvidence_testRunId_idx" ON "PhotoEvidence"("testRunId");
CREATE UNIQUE INDEX "MachineSetting_machineId_key_key" ON "MachineSetting"("machineId", "key");

ALTER TABLE "OperatorPermission" ADD CONSTRAINT "OperatorPermission_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Operator"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MaintenanceChecklist" ADD CONSTRAINT "MaintenanceChecklist_configuredById_fkey" FOREIGN KEY ("configuredById") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MaintenanceTask" ADD CONSTRAINT "MaintenanceTask_machineId_fkey" FOREIGN KEY ("machineId") REFERENCES "Machine"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "MaintenanceTask" ADD CONSTRAINT "MaintenanceTask_checklistId_fkey" FOREIGN KEY ("checklistId") REFERENCES "MaintenanceChecklist"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "MaintenanceTask" ADD CONSTRAINT "MaintenanceTask_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "MaintenanceTask" ADD CONSTRAINT "MaintenanceTask_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "Operator"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ServiceLog" ADD CONSTRAINT "ServiceLog_machineId_fkey" FOREIGN KEY ("machineId") REFERENCES "Machine"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ServiceLog" ADD CONSTRAINT "ServiceLog_maintenanceTaskId_fkey" FOREIGN KEY ("maintenanceTaskId") REFERENCES "MaintenanceTask"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ServiceLog" ADD CONSTRAINT "ServiceLog_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ServiceLog" ADD CONSTRAINT "ServiceLog_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "Operator"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TestRun" ADD CONSTRAINT "TestRun_machineId_fkey" FOREIGN KEY ("machineId") REFERENCES "Machine"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "TestRun" ADD CONSTRAINT "TestRun_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_machineId_fkey" FOREIGN KEY ("machineId") REFERENCES "Machine"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_testRunId_fkey" FOREIGN KEY ("testRunId") REFERENCES "TestRun"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PhotoEvidence" ADD CONSTRAINT "PhotoEvidence_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "PhotoEvidence" ADD CONSTRAINT "PhotoEvidence_maintenanceTaskId_fkey" FOREIGN KEY ("maintenanceTaskId") REFERENCES "MaintenanceTask"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "PhotoEvidence" ADD CONSTRAINT "PhotoEvidence_serviceLogId_fkey" FOREIGN KEY ("serviceLogId") REFERENCES "ServiceLog"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "PhotoEvidence" ADD CONSTRAINT "PhotoEvidence_testRunId_fkey" FOREIGN KEY ("testRunId") REFERENCES "TestRun"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MachineSetting" ADD CONSTRAINT "MachineSetting_machineId_fkey" FOREIGN KEY ("machineId") REFERENCES "Machine"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "MachineSetting" ADD CONSTRAINT "MachineSetting_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "Operator"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
